package proxy.shm.io;
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
//
//                    Source Code Generated by
//                           CA Gen 8.6
//
//    Copyright (c) 2021 CA Technologies. All rights reserved.
//
//    Name: SH61S000_IA                      Date: 2021/01/06
//    User: ssrivastava                      Time: 17:14:16
//
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
// Import Statements
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
import java.lang.*;
import java.io.*;
import java.util.*;
import java.math.*;
import java.sql.*;
import com.ca.gen.vwrt.*;
import com.ca.gen.vwrt.types.*;
import com.ca.gen.vwrt.vdf.*;
import com.ca.gen.csu.exception.*;

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
// START OF IMPORT VIEW
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
/**
 * Internal data view storage for: SH61S000_IA
 **/
public class SH61S000_IA extends ViewBase implements IImportView, Serializable
{
  static VDF localVdf = null;
  
  // Entity View: IN
  //        Type: ISHM1_SHIPMENT
  /**
   * Attribute missing flag for: InIshm1ShipmentInstId
   **/
  public char InIshm1ShipmentInstId_AS;
  /**
   * Attribute for: InIshm1ShipmentInstId
   * Domain: Number
   * Length: 15
   * Decimal Places: 0
   * Decimal Precision: N
   **/
  public double InIshm1ShipmentInstId;
  /**
   * Attribute missing flag for: InIshm1ShipmentProNbrTxt
   **/
  public char InIshm1ShipmentProNbrTxt_AS;
  /**
   * Attribute for: InIshm1ShipmentProNbrTxt
   * Domain: Text
   * Length: 11
   * Varying Length: N
   **/
  public String InIshm1ShipmentProNbrTxt;
  // Entity View: IN_EVENT
  //        Type: ISHM1_EVENT
  /**
   * Attribute missing flag for: InEventIshm1EventSubTypCd
   **/
  public char InEventIshm1EventSubTypCd_AS;
  /**
   * Attribute for: InEventIshm1EventSubTypCd
   * Domain: Text
   * Length: 2
   * Varying Length: N
   **/
  public String InEventIshm1EventSubTypCd;
  // Entity View: IN_PARENT
  //        Type: ISHM1_SHIPMENT
  /**
   * Attribute missing flag for: InParentIshm1ShipmentInstId
   **/
  public char InParentIshm1ShipmentInstId_AS;
  /**
   * Attribute for: InParentIshm1ShipmentInstId
   * Domain: Number
   * Length: 15
   * Decimal Places: 0
   * Decimal Precision: N
   **/
  public double InParentIshm1ShipmentInstId;
  /**
   * Attribute missing flag for: InParentIshm1ShipmentProNbrTxt
   **/
  public char InParentIshm1ShipmentProNbrTxt_AS;
  /**
   * Attribute for: InParentIshm1ShipmentProNbrTxt
   * Domain: Text
   * Length: 11
   * Varying Length: N
   **/
  public String InParentIshm1ShipmentProNbrTxt;
  // Entity View: IN_SHORT
  //        Type: ISHM1_MOVEMENT_EXCEPTION
  /**
   * Attribute missing flag for: InShortIshm1MovementExceptionPcsCnt
   **/
  public char InShortIshm1MovementExceptionPcsCnt_AS;
  /**
   * Attribute for: InShortIshm1MovementExceptionPcsCnt
   * Domain: Number
   * Length: 7
   * Decimal Places: 0
   * Decimal Precision: N
   **/
  public int InShortIshm1MovementExceptionPcsCnt;
  // Entity View: IN_TRAILER_XREF
  //        Type: IOPT1_TRLR_LOAD_INST
  /**
   * Attribute missing flag for: InTrailerXrefIopt1TrlrLoadInstTrlrLdMbfEqpId
   **/
  public char InTrailerXrefIopt1TrlrLoadInstTrlrLdMbfEqpId_AS;
  /**
   * Attribute for: InTrailerXrefIopt1TrlrLoadInstTrlrLdMbfEqpId
   * Domain: Text
   * Length: 8
   * Varying Length: N
   **/
  public String InTrailerXrefIopt1TrlrLoadInstTrlrLdMbfEqpId;
  // Entity View: IN_CONTROL
  //        Type: ISHS1_SHARED_SERVICES
  /**
   * Attribute missing flag for: InControlIshs1SharedServicesLongUserid
   **/
  public char InControlIshs1SharedServicesLongUserid_AS;
  /**
   * Attribute for: InControlIshs1SharedServicesLongUserid
   * Domain: Text
   * Length: 15
   * Varying Length: N
   **/
  public String InControlIshs1SharedServicesLongUserid;
  /**
   * Default Constructor
   **/
  
  public SH61S000_IA()
  {
    reset();
  }
  /**
   * Copy Constructor
   **/
  
  public SH61S000_IA(SH61S000_IA orig)
  {
    copyFrom(orig);
  }
  /**
   * Static instance creator function
   **/
  
  public static SH61S000_IA getInstance()
  {
    return new SH61S000_IA();
  }
  /**
   * Static free instance method
   **/
  
  public void freeInstance()
  {
  }
  /**
   * clone constructor
   **/
  
  @Override public Object clone()
  	throws CloneNotSupportedException
  {
    return(new SH61S000_IA(this));
  }
  /**
   * Resets all properties to the defaults.
   **/
  
  public void reset()
  {
    InIshm1ShipmentInstId_AS = ' ';
    InIshm1ShipmentInstId = 0.0;
    InIshm1ShipmentProNbrTxt_AS = ' ';
    InIshm1ShipmentProNbrTxt = "           ";
    InEventIshm1EventSubTypCd_AS = ' ';
    InEventIshm1EventSubTypCd = "  ";
    InParentIshm1ShipmentInstId_AS = ' ';
    InParentIshm1ShipmentInstId = 0.0;
    InParentIshm1ShipmentProNbrTxt_AS = ' ';
    InParentIshm1ShipmentProNbrTxt = "           ";
    InShortIshm1MovementExceptionPcsCnt_AS = ' ';
    InShortIshm1MovementExceptionPcsCnt = 0;
    InTrailerXrefIopt1TrlrLoadInstTrlrLdMbfEqpId_AS = ' ';
    InTrailerXrefIopt1TrlrLoadInstTrlrLdMbfEqpId = "        ";
    InControlIshs1SharedServicesLongUserid_AS = ' ';
    InControlIshs1SharedServicesLongUserid = "               ";
  }
  /**
   * Gets the VDF array for the instance, initialized.
   **/
  
  public static VDF getViewDefinition()
  {
    if ( localVdf == null )
    {
      VDFEntry [] vdfEntries = {
        new VDFEntry((int)1, "", "InIshm1Shipment", "Ishm1Shipment", "InstId", VDFEntry.TYPE_DOUBLE, (short)1, (short)0, 15, (short)
          0, null), 
        new VDFEntry((int)2, "", "InIshm1Shipment", "Ishm1Shipment", "ProNbrTxt", VDFEntry.TYPE_STRING, (short)1, (short)0, 11, (
          short)0, null), 
        new VDFEntry((int)3, "", "InEventIshm1Event", "Ishm1Event", "SubTypCd", VDFEntry.TYPE_STRING, (short)1, (short)0, 2, (short)
          0, null), 
        new VDFEntry((int)4, "", "InParentIshm1Shipment", "Ishm1Shipment", "InstId", VDFEntry.TYPE_DOUBLE, (short)1, (short)0, 15, (
          short)0, null), 
        new VDFEntry((int)5, "", "InParentIshm1Shipment", "Ishm1Shipment", "ProNbrTxt", VDFEntry.TYPE_STRING, (short)1, (short)0, 11,
           (short)0, null), 
        new VDFEntry((int)6, "", "InShortIshm1MovementException", "Ishm1MovementException", "PcsCnt", VDFEntry.TYPE_INT, (short)1, (
          short)0, 8, (short)0, null), 
        new VDFEntry((int)7, "", "InTrailerXrefIopt1TrlrLoadInst", "Iopt1TrlrLoadInst", "TrlrLdMbfEqpId", VDFEntry.TYPE_STRING, (
          short)1, (short)0, 8, (short)0, null), 
        new VDFEntry((int)8, "", "InControlIshs1SharedServices", "Ishs1SharedServices", "LongUserid", VDFEntry.TYPE_STRING, (short)1,
           (short)0, 15, (short)0, null), 
      };
      localVdf = new VDF(vdfEntries);
    }
    try {
      VDF result = (VDF)localVdf.clone();
      result.initViewData();
      return result;
    } catch( CloneNotSupportedException e ) {
      return null;
    }
  }
  
  /**
   * Gets the VDF version of the current state of the instance.
   **/
  public VDF getVDF()
  {
    VDF vdf = getViewDefinition();
    // predicate view item
    vdf.getEntries()[0].getDataValue().setObject(new Double(InIshm1ShipmentInstId));
    // predicate view item
    vdf.getEntries()[1].getDataValue().setObject(InIshm1ShipmentProNbrTxt);
    // predicate view item
    vdf.getEntries()[2].getDataValue().setObject(InEventIshm1EventSubTypCd);
    // predicate view item
    vdf.getEntries()[3].getDataValue().setObject(new Double(InParentIshm1ShipmentInstId));
    // predicate view item
    vdf.getEntries()[4].getDataValue().setObject(InParentIshm1ShipmentProNbrTxt);
    // predicate view item
    vdf.getEntries()[5].getDataValue().setObject(new Integer(InShortIshm1MovementExceptionPcsCnt));
    // predicate view item
    vdf.getEntries()[6].getDataValue().setObject(InTrailerXrefIopt1TrlrLoadInstTrlrLdMbfEqpId);
    // predicate view item
    vdf.getEntries()[7].getDataValue().setObject(InControlIshs1SharedServicesLongUserid);
    return(vdf);
  }
  
  /**
   * Sets the current state of the instance to the VDF version.
   **/
  public void setFromVDF(VDF vdf)
  {
    // predicate view item
    if ( vdf.getEntries()[0].getDataValue().getObject() != null )
    {
      InIshm1ShipmentInstId = ((Double)vdf.getEntries()[0].getDataValue().getObject()).doubleValue();
    }
    else 
    {
      InIshm1ShipmentInstId = 0.0;
    }
    // predicate view item
    if ( vdf.getEntries()[1].getDataValue().getObject() != null )
    {
      InIshm1ShipmentProNbrTxt = ((String)vdf.getEntries()[1].getDataValue().getObject());
    }
    else 
    {
      InIshm1ShipmentProNbrTxt = "           ";
    }
    // predicate view item
    if ( vdf.getEntries()[2].getDataValue().getObject() != null )
    {
      InEventIshm1EventSubTypCd = ((String)vdf.getEntries()[2].getDataValue().getObject());
    }
    else 
    {
      InEventIshm1EventSubTypCd = "  ";
    }
    // predicate view item
    if ( vdf.getEntries()[3].getDataValue().getObject() != null )
    {
      InParentIshm1ShipmentInstId = ((Double)vdf.getEntries()[3].getDataValue().getObject()).doubleValue();
    }
    else 
    {
      InParentIshm1ShipmentInstId = 0.0;
    }
    // predicate view item
    if ( vdf.getEntries()[4].getDataValue().getObject() != null )
    {
      InParentIshm1ShipmentProNbrTxt = ((String)vdf.getEntries()[4].getDataValue().getObject());
    }
    else 
    {
      InParentIshm1ShipmentProNbrTxt = "           ";
    }
    // predicate view item
    if ( vdf.getEntries()[5].getDataValue().getObject() != null )
    {
      InShortIshm1MovementExceptionPcsCnt = ((Integer)vdf.getEntries()[5].getDataValue().getObject()).intValue();
    }
    else 
    {
      InShortIshm1MovementExceptionPcsCnt = 0;
    }
    // predicate view item
    if ( vdf.getEntries()[6].getDataValue().getObject() != null )
    {
      InTrailerXrefIopt1TrlrLoadInstTrlrLdMbfEqpId = ((String)vdf.getEntries()[6].getDataValue().getObject());
    }
    else 
    {
      InTrailerXrefIopt1TrlrLoadInstTrlrLdMbfEqpId = "        ";
    }
    // predicate view item
    if ( vdf.getEntries()[7].getDataValue().getObject() != null )
    {
      InControlIshs1SharedServicesLongUserid = ((String)vdf.getEntries()[7].getDataValue().getObject());
    }
    else 
    {
      InControlIshs1SharedServicesLongUserid = "               ";
    }
  }
  
  /**
   * Sets the current instance based on the passed view.
   **/
  public void copyFrom(IImportView orig)
  {
    this.copyFrom((SH61S000_IA) orig);
  }
  
  /**
   * Sets the current instance based on the passed view.
   **/
  public void copyFrom(SH61S000_IA orig)
  {
    InIshm1ShipmentInstId_AS = orig.InIshm1ShipmentInstId_AS;
    InIshm1ShipmentInstId = orig.InIshm1ShipmentInstId;
    InIshm1ShipmentProNbrTxt_AS = orig.InIshm1ShipmentProNbrTxt_AS;
    InIshm1ShipmentProNbrTxt = orig.InIshm1ShipmentProNbrTxt;
    InEventIshm1EventSubTypCd_AS = orig.InEventIshm1EventSubTypCd_AS;
    InEventIshm1EventSubTypCd = orig.InEventIshm1EventSubTypCd;
    InParentIshm1ShipmentInstId_AS = orig.InParentIshm1ShipmentInstId_AS;
    InParentIshm1ShipmentInstId = orig.InParentIshm1ShipmentInstId;
    InParentIshm1ShipmentProNbrTxt_AS = orig.InParentIshm1ShipmentProNbrTxt_AS;
    InParentIshm1ShipmentProNbrTxt = orig.InParentIshm1ShipmentProNbrTxt;
    InShortIshm1MovementExceptionPcsCnt_AS = orig.InShortIshm1MovementExceptionPcsCnt_AS;
    InShortIshm1MovementExceptionPcsCnt = orig.InShortIshm1MovementExceptionPcsCnt;
    InTrailerXrefIopt1TrlrLoadInstTrlrLdMbfEqpId_AS = orig.InTrailerXrefIopt1TrlrLoadInstTrlrLdMbfEqpId_AS;
    InTrailerXrefIopt1TrlrLoadInstTrlrLdMbfEqpId = orig.InTrailerXrefIopt1TrlrLoadInstTrlrLdMbfEqpId;
    InControlIshs1SharedServicesLongUserid_AS = orig.InControlIshs1SharedServicesLongUserid_AS;
    InControlIshs1SharedServicesLongUserid = orig.InControlIshs1SharedServicesLongUserid;
  }
}
