package proxy.shm.io;
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
//
//                    Source Code Generated by
//                           CA Gen 8.6
//
//    Copyright (c) 2021 CA Technologies. All rights reserved.
//
//    Name: SH62S000_OA                      Date: 2021/04/27
//    User: cadoucet                         Time: 16:07:21
//
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
// Import Statements
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
import java.lang.*;
import java.io.*;
import java.util.*;
import java.math.*;
import java.sql.*;
import com.ca.gen.vwrt.*;
import com.ca.gen.vwrt.types.*;
import com.ca.gen.vwrt.vdf.*;
import com.ca.gen.csu.exception.*;

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
// START OF EXPORT VIEW
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
/**
 * Internal data view storage for: SH62S000_OA
 **/
public class SH62S000_OA extends ViewBase implements IExportView, Serializable
{
  static VDF localVdf = null;
  
  // Entity View: OUT_ERROR
  //        Type: ISHS1_SHARED_SERVICES
  /**
   * Attribute missing flag for: OutErrorIshs1SharedServicesDataStoreStatusCd
   **/
  public char OutErrorIshs1SharedServicesDataStoreStatusCd_AS;
  /**
   * Dynamic attribute for: OutErrorIshs1SharedServicesDataStoreStatusCd
   **/
  public DynamicAttr OutErrorIshs1SharedServicesDataStoreStatusCd_AT;
  /**
   * Attribute for: OutErrorIshs1SharedServicesDataStoreStatusCd
   * Domain: Text
   * Length: 1
   * Varying Length: N
   **/
  public String OutErrorIshs1SharedServicesDataStoreStatusCd;
  /**
   * Attribute missing flag for: OutErrorIshs1SharedServicesOriginServerId
   **/
  public char OutErrorIshs1SharedServicesOriginServerId_AS;
  /**
   * Dynamic attribute for: OutErrorIshs1SharedServicesOriginServerId
   **/
  public DynamicAttr OutErrorIshs1SharedServicesOriginServerId_AT;
  /**
   * Attribute for: OutErrorIshs1SharedServicesOriginServerId
   * Domain: Number
   * Length: 15
   * Decimal Places: 0
   * Decimal Precision: N
   **/
  public double OutErrorIshs1SharedServicesOriginServerId;
  /**
   * Attribute missing flag for: OutErrorIshs1SharedServicesContextStringTx
   **/
  public char OutErrorIshs1SharedServicesContextStringTx_AS;
  /**
   * Dynamic attribute for: OutErrorIshs1SharedServicesContextStringTx
   **/
  public DynamicAttr OutErrorIshs1SharedServicesContextStringTx_AT;
  /**
   * Attribute for: OutErrorIshs1SharedServicesContextStringTx
   * Domain: Text
   * Length: 255
   * Varying Length: Y
   **/
  public String OutErrorIshs1SharedServicesContextStringTx;
  /**
   * Attribute missing flag for: OutErrorIshs1SharedServicesReturnCd
   **/
  public char OutErrorIshs1SharedServicesReturnCd_AS;
  /**
   * Dynamic attribute for: OutErrorIshs1SharedServicesReturnCd
   **/
  public DynamicAttr OutErrorIshs1SharedServicesReturnCd_AT;
  /**
   * Attribute for: OutErrorIshs1SharedServicesReturnCd
   * Domain: Number
   * Length: 5
   * Decimal Places: 0
   * Decimal Precision: N
   **/
  public int OutErrorIshs1SharedServicesReturnCd;
  /**
   * Attribute missing flag for: OutErrorIshs1SharedServicesReasonCd
   **/
  public char OutErrorIshs1SharedServicesReasonCd_AS;
  /**
   * Dynamic attribute for: OutErrorIshs1SharedServicesReasonCd
   **/
  public DynamicAttr OutErrorIshs1SharedServicesReasonCd_AT;
  /**
   * Attribute for: OutErrorIshs1SharedServicesReasonCd
   * Domain: Number
   * Length: 5
   * Decimal Places: 0
   * Decimal Precision: N
   **/
  public int OutErrorIshs1SharedServicesReasonCd;
  /**
   * Default Constructor
   **/
  
  public SH62S000_OA()
  {
    reset();
  }
  /**
   * Copy Constructor
   **/
  
  public SH62S000_OA(SH62S000_OA orig)
  {
    copyFrom(orig);
  }
  /**
   * Static instance creator function
   **/
  
  public static SH62S000_OA getInstance()
  {
    return new SH62S000_OA();
  }
  /**
   * Static free instance method
   **/
  
  public void freeInstance()
  {
  }
  /**
   * clone constructor
   **/
  
  @Override public Object clone()
  	throws CloneNotSupportedException
  {
    return(new SH62S000_OA(this));
  }
  /**
   * Resets all properties to the defaults.
   **/
  
  public void reset()
  {
    OutErrorIshs1SharedServicesDataStoreStatusCd_AT = null;
    OutErrorIshs1SharedServicesDataStoreStatusCd_AS = ' ';
    OutErrorIshs1SharedServicesDataStoreStatusCd = " ";
    OutErrorIshs1SharedServicesOriginServerId_AT = null;
    OutErrorIshs1SharedServicesOriginServerId_AS = ' ';
    OutErrorIshs1SharedServicesOriginServerId = 0.0;
    OutErrorIshs1SharedServicesContextStringTx_AT = null;
    OutErrorIshs1SharedServicesContextStringTx_AS = ' ';
    OutErrorIshs1SharedServicesContextStringTx = "";
    OutErrorIshs1SharedServicesReturnCd_AT = null;
    OutErrorIshs1SharedServicesReturnCd_AS = ' ';
    OutErrorIshs1SharedServicesReturnCd = 0;
    OutErrorIshs1SharedServicesReasonCd_AT = null;
    OutErrorIshs1SharedServicesReasonCd_AS = ' ';
    OutErrorIshs1SharedServicesReasonCd = 0;
  }
  /**
   * Gets the VDF array for the instance, initialized.
   **/
  
  public static VDF getViewDefinition()
  {
    if ( localVdf == null )
    {
      VDFEntry [] vdfEntries = {
        new VDFEntry((int)1, "", "OutErrorIshs1SharedServices", "Ishs1SharedServices", "DataStoreStatusCd", VDFEntry.TYPE_STRING, (
          short)1, (short)0, 1, (short)0, null), 
        new VDFEntry((int)2, "", "OutErrorIshs1SharedServices", "Ishs1SharedServices", "OriginServerId", VDFEntry.TYPE_DOUBLE, (
          short)1, (short)0, 15, (short)0, null), 
        new VDFEntry((int)3, "", "OutErrorIshs1SharedServices", "Ishs1SharedServices", "ContextStringTx", VDFEntry.TYPE_STRING, (
          short)1, (short)0, 255, (short)0, null), 
        new VDFEntry((int)4, "", "OutErrorIshs1SharedServices", "Ishs1SharedServices", "ReturnCd", VDFEntry.TYPE_INT, (short)1, (
          short)0, 8, (short)0, null), 
        new VDFEntry((int)5, "", "OutErrorIshs1SharedServices", "Ishs1SharedServices", "ReasonCd", VDFEntry.TYPE_INT, (short)1, (
          short)0, 8, (short)0, null), 
      };
      localVdf = new VDF(vdfEntries);
    }
    try {
      VDF result = (VDF)localVdf.clone();
      result.initViewData();
      return result;
    } catch( CloneNotSupportedException e ) {
      return null;
    }
  }
  
  /**
   * Sets the current state of the instance to the VDF version.
   **/
  public void setFromVDF(VDF vdf)
  {
    // predicate view item
    if ( vdf.getEntries()[0].getDataValue().getObject() != null )
    {
      OutErrorIshs1SharedServicesDataStoreStatusCd = ((String)vdf.getEntries()[0].getDataValue().getObject());
    }
    else 
    {
      OutErrorIshs1SharedServicesDataStoreStatusCd = " ";
    }
    // predicate view item
    if ( vdf.getEntries()[1].getDataValue().getObject() != null )
    {
      OutErrorIshs1SharedServicesOriginServerId = ((Double)vdf.getEntries()[1].getDataValue().getObject()).doubleValue();
    }
    else 
    {
      OutErrorIshs1SharedServicesOriginServerId = 0.0;
    }
    // predicate view item
    if ( vdf.getEntries()[2].getDataValue().getObject() != null )
    {
      OutErrorIshs1SharedServicesContextStringTx = ((String)vdf.getEntries()[2].getDataValue().getObject());
    }
    else 
    {
      OutErrorIshs1SharedServicesContextStringTx = "";
    }
    // predicate view item
    if ( vdf.getEntries()[3].getDataValue().getObject() != null )
    {
      OutErrorIshs1SharedServicesReturnCd = ((Integer)vdf.getEntries()[3].getDataValue().getObject()).intValue();
    }
    else 
    {
      OutErrorIshs1SharedServicesReturnCd = 0;
    }
    // predicate view item
    if ( vdf.getEntries()[4].getDataValue().getObject() != null )
    {
      OutErrorIshs1SharedServicesReasonCd = ((Integer)vdf.getEntries()[4].getDataValue().getObject()).intValue();
    }
    else 
    {
      OutErrorIshs1SharedServicesReasonCd = 0;
    }
  }
  
  /**
   * Gets the VDF version of the current state of the instance.
   **/
  public VDF getVDF()
  {
    VDF vdf = getViewDefinition();
    // predicate view item
    vdf.getEntries()[0].getDataValue().setObject(OutErrorIshs1SharedServicesDataStoreStatusCd);
    // predicate view item
    vdf.getEntries()[1].getDataValue().setObject(new Double(OutErrorIshs1SharedServicesOriginServerId));
    // predicate view item
    vdf.getEntries()[2].getDataValue().setObject(OutErrorIshs1SharedServicesContextStringTx);
    // predicate view item
    vdf.getEntries()[3].getDataValue().setObject(new Integer(OutErrorIshs1SharedServicesReturnCd));
    // predicate view item
    vdf.getEntries()[4].getDataValue().setObject(new Integer(OutErrorIshs1SharedServicesReasonCd));
    return(vdf);
  }
  
  /**
   * Sets the current instance based on the passed view.
   **/
  public void copyFrom(IExportView orig)
  {
    this.copyFrom((SH62S000_OA) orig);
  }
  
  /**
   * Sets the current instance based on the passed view.
   **/
  public void copyFrom(SH62S000_OA orig)
  {
    OutErrorIshs1SharedServicesDataStoreStatusCd_AT = orig.OutErrorIshs1SharedServicesDataStoreStatusCd_AT;
    OutErrorIshs1SharedServicesDataStoreStatusCd_AS = orig.OutErrorIshs1SharedServicesDataStoreStatusCd_AS;
    OutErrorIshs1SharedServicesDataStoreStatusCd = orig.OutErrorIshs1SharedServicesDataStoreStatusCd;
    OutErrorIshs1SharedServicesOriginServerId_AT = orig.OutErrorIshs1SharedServicesOriginServerId_AT;
    OutErrorIshs1SharedServicesOriginServerId_AS = orig.OutErrorIshs1SharedServicesOriginServerId_AS;
    OutErrorIshs1SharedServicesOriginServerId = orig.OutErrorIshs1SharedServicesOriginServerId;
    OutErrorIshs1SharedServicesContextStringTx_AT = orig.OutErrorIshs1SharedServicesContextStringTx_AT;
    OutErrorIshs1SharedServicesContextStringTx_AS = orig.OutErrorIshs1SharedServicesContextStringTx_AS;
    OutErrorIshs1SharedServicesContextStringTx = orig.OutErrorIshs1SharedServicesContextStringTx;
    OutErrorIshs1SharedServicesReturnCd_AT = orig.OutErrorIshs1SharedServicesReturnCd_AT;
    OutErrorIshs1SharedServicesReturnCd_AS = orig.OutErrorIshs1SharedServicesReturnCd_AS;
    OutErrorIshs1SharedServicesReturnCd = orig.OutErrorIshs1SharedServicesReturnCd;
    OutErrorIshs1SharedServicesReasonCd_AT = orig.OutErrorIshs1SharedServicesReasonCd_AT;
    OutErrorIshs1SharedServicesReasonCd_AS = orig.OutErrorIshs1SharedServicesReasonCd_AS;
    OutErrorIshs1SharedServicesReasonCd = orig.OutErrorIshs1SharedServicesReasonCd;
  }
}
