package proxy.shm.io;
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
//
//                    Source Code Generated by
//                           CA Gen 8.6
//
//    Copyright (c) 2021 CA Technologies. All rights reserved.
//
//    Name: SH62S000_IA                      Date: 2021/04/27
//    User: cadoucet                         Time: 16:07:21
//
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
// Import Statements
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
import java.lang.*;
import java.io.*;
import java.util.*;
import java.math.*;
import java.sql.*;
import com.ca.gen.vwrt.*;
import com.ca.gen.vwrt.types.*;
import com.ca.gen.vwrt.vdf.*;
import com.ca.gen.csu.exception.*;

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
// START OF IMPORT VIEW
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
/**
 * Internal data view storage for: SH62S000_IA
 **/
public class SH62S000_IA extends ViewBase implements IImportView, Serializable
{
  static VDF localVdf = null;
  
  // Entity View: IN
  //        Type: ISHM1_SHIPMENT
  /**
   * Attribute missing flag for: InIshm1ShipmentInstId
   **/
  public char InIshm1ShipmentInstId_AS;
  /**
   * Attribute for: InIshm1ShipmentInstId
   * Domain: Number
   * Length: 15
   * Decimal Places: 0
   * Decimal Precision: N
   **/
  public double InIshm1ShipmentInstId;
  /**
   * Attribute missing flag for: InIshm1ShipmentApptRqrdInd
   **/
  public char InIshm1ShipmentApptRqrdInd_AS;
  /**
   * Attribute for: InIshm1ShipmentApptRqrdInd
   * Domain: Text
   * Length: 1
   * Varying Length: N
   **/
  public String InIshm1ShipmentApptRqrdInd;
  // Entity View: IN_CONTROL
  //        Type: ISHS1_SHARED_SERVICES
  /**
   * Attribute missing flag for: InControlIshs1SharedServicesLongUserid
   **/
  public char InControlIshs1SharedServicesLongUserid_AS;
  /**
   * Attribute for: InControlIshs1SharedServicesLongUserid
   * Domain: Text
   * Length: 15
   * Varying Length: N
   **/
  public String InControlIshs1SharedServicesLongUserid;
  /**
   * Default Constructor
   **/
  
  public SH62S000_IA()
  {
    reset();
  }
  /**
   * Copy Constructor
   **/
  
  public SH62S000_IA(SH62S000_IA orig)
  {
    copyFrom(orig);
  }
  /**
   * Static instance creator function
   **/
  
  public static SH62S000_IA getInstance()
  {
    return new SH62S000_IA();
  }
  /**
   * Static free instance method
   **/
  
  public void freeInstance()
  {
  }
  /**
   * clone constructor
   **/
  
  @Override public Object clone()
  	throws CloneNotSupportedException
  {
    return(new SH62S000_IA(this));
  }
  /**
   * Resets all properties to the defaults.
   **/
  
  public void reset()
  {
    InIshm1ShipmentInstId_AS = ' ';
    InIshm1ShipmentInstId = 0.0;
    InIshm1ShipmentApptRqrdInd_AS = ' ';
    InIshm1ShipmentApptRqrdInd = " ";
    InControlIshs1SharedServicesLongUserid_AS = ' ';
    InControlIshs1SharedServicesLongUserid = "               ";
  }
  /**
   * Gets the VDF array for the instance, initialized.
   **/
  
  public static VDF getViewDefinition()
  {
    if ( localVdf == null )
    {
      VDFEntry [] vdfEntries = {
        new VDFEntry((int)1, "", "InIshm1Shipment", "Ishm1Shipment", "InstId", VDFEntry.TYPE_DOUBLE, (short)1, (short)0, 15, (short)
          0, null), 
        new VDFEntry((int)2, "", "InIshm1Shipment", "Ishm1Shipment", "ApptRqrdInd", VDFEntry.TYPE_STRING, (short)1, (short)0, 1, (
          short)0, null), 
        new VDFEntry((int)3, "", "InControlIshs1SharedServices", "Ishs1SharedServices", "LongUserid", VDFEntry.TYPE_STRING, (short)1,
           (short)0, 15, (short)0, null), 
      };
      localVdf = new VDF(vdfEntries);
    }
    try {
      VDF result = (VDF)localVdf.clone();
      result.initViewData();
      return result;
    } catch( CloneNotSupportedException e ) {
      return null;
    }
  }
  
  /**
   * Gets the VDF version of the current state of the instance.
   **/
  public VDF getVDF()
  {
    VDF vdf = getViewDefinition();
    // predicate view item
    vdf.getEntries()[0].getDataValue().setObject(new Double(InIshm1ShipmentInstId));
    // predicate view item
    vdf.getEntries()[1].getDataValue().setObject(InIshm1ShipmentApptRqrdInd);
    // predicate view item
    vdf.getEntries()[2].getDataValue().setObject(InControlIshs1SharedServicesLongUserid);
    return(vdf);
  }
  
  /**
   * Sets the current state of the instance to the VDF version.
   **/
  public void setFromVDF(VDF vdf)
  {
    // predicate view item
    if ( vdf.getEntries()[0].getDataValue().getObject() != null )
    {
      InIshm1ShipmentInstId = ((Double)vdf.getEntries()[0].getDataValue().getObject()).doubleValue();
    }
    else 
    {
      InIshm1ShipmentInstId = 0.0;
    }
    // predicate view item
    if ( vdf.getEntries()[1].getDataValue().getObject() != null )
    {
      InIshm1ShipmentApptRqrdInd = ((String)vdf.getEntries()[1].getDataValue().getObject());
    }
    else 
    {
      InIshm1ShipmentApptRqrdInd = " ";
    }
    // predicate view item
    if ( vdf.getEntries()[2].getDataValue().getObject() != null )
    {
      InControlIshs1SharedServicesLongUserid = ((String)vdf.getEntries()[2].getDataValue().getObject());
    }
    else 
    {
      InControlIshs1SharedServicesLongUserid = "               ";
    }
  }
  
  /**
   * Sets the current instance based on the passed view.
   **/
  public void copyFrom(IImportView orig)
  {
    this.copyFrom((SH62S000_IA) orig);
  }
  
  /**
   * Sets the current instance based on the passed view.
   **/
  public void copyFrom(SH62S000_IA orig)
  {
    InIshm1ShipmentInstId_AS = orig.InIshm1ShipmentInstId_AS;
    InIshm1ShipmentInstId = orig.InIshm1ShipmentInstId;
    InIshm1ShipmentApptRqrdInd_AS = orig.InIshm1ShipmentApptRqrdInd_AS;
    InIshm1ShipmentApptRqrdInd = orig.InIshm1ShipmentApptRqrdInd;
    InControlIshs1SharedServicesLongUserid_AS = orig.InControlIshs1SharedServicesLongUserid_AS;
    InControlIshs1SharedServicesLongUserid = orig.InControlIshs1SharedServicesLongUserid;
  }
}
