package proxy.mfl.io;
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
//
//                    Source Code Generated by
//                           CA Gen 8.5
//
//    Copyright (c) 2016 CA Technologies. All rights reserved.
//
//    Name: MF2AS000_IA                      Date: 2016/09/15
//    User: djrichard                        Time: 08:48:22
//
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
// Import Statements
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
import java.lang.*;
import java.io.*;
import java.util.*;
import java.math.*;
import java.sql.*;
import com.ca.gen85.vwrt.*;
import com.ca.gen85.vwrt.types.*;
import com.ca.gen85.vwrt.vdf.*;
import com.ca.gen85.csu.exception.*;

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
// START OF IMPORT VIEW
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
/**
 * Internal data view storage for: MF2AS000_IA
 **/
public class MF2AS000_IA extends ViewBase implements IImportView, Serializable
{
  static VDF localVdf = null;
  
  // Entity View: IN_DEST_SIC_CD
  //        Type: ISHS1_SHARED_SERVICES
  /**
   * Attribute missing flag for: InDestSicCdIshs1SharedServicesString3Tx
   **/
  public char InDestSicCdIshs1SharedServicesString3Tx_AS;
  /**
   * Attribute for: InDestSicCdIshs1SharedServicesString3Tx
   * Domain: Text
   * Length: 3
   * Varying Length: N
   **/
  public String InDestSicCdIshs1SharedServicesString3Tx;
  // Entity View: IN_PRINTER_CODE
  //        Type: ISHS1_SHARED_SERVICES
  /**
   * Attribute missing flag for: InPrinterCodeIshs1SharedServicesString12Tx
   **/
  public char InPrinterCodeIshs1SharedServicesString12Tx_AS;
  /**
   * Attribute for: InPrinterCodeIshs1SharedServicesString12Tx
   * Domain: Text
   * Length: 12
   * Varying Length: N
   **/
  public String InPrinterCodeIshs1SharedServicesString12Tx;
  // Entity View: IN_REPORT_TYP
  //        Type: ISHS1_SHARED_SERVICES
  /**
   * Attribute missing flag for: InReportTypIshs1SharedServicesString8Tx
   **/
  public char InReportTypIshs1SharedServicesString8Tx_AS;
  /**
   * Attribute for: InReportTypIshs1SharedServicesString8Tx
   * Domain: Text
   * Length: 8
   * Varying Length: N
   **/
  public String InReportTypIshs1SharedServicesString8Tx;
  // Entity View: IN_FORM_TYP
  //        Type: ISHS1_SHARED_SERVICES
  /**
   * Attribute missing flag for: InFormTypIshs1SharedServicesString8Tx
   **/
  public char InFormTypIshs1SharedServicesString8Tx_AS;
  /**
   * Attribute for: InFormTypIshs1SharedServicesString8Tx
   * Domain: Text
   * Length: 8
   * Varying Length: N
   **/
  public String InFormTypIshs1SharedServicesString8Tx;
  // Entity View: IN_REPRINT_IND
  //        Type: ISHS1_SHARED_SERVICES
  /**
   * Attribute missing flag for: InReprintIndIshs1SharedServicesFlagFg
   **/
  public char InReprintIndIshs1SharedServicesFlagFg_AS;
  /**
   * Attribute for: InReprintIndIshs1SharedServicesFlagFg
   * Domain: Text
   * Length: 1
   * Varying Length: N
   **/
  public String InReprintIndIshs1SharedServicesFlagFg;
  // Entity View: IN_INCLUDE_PROS_DESTINED_IND
  //        Type: ISHS1_SHARED_SERVICES
  /**
   * Attribute missing flag for: InIncludeProsDestinedIndIshs1SharedServicesFlagFg
   **/
  public char InIncludeProsDestinedIndIshs1SharedServicesFlagFg_AS;
  /**
   * Attribute for: InIncludeProsDestinedIndIshs1SharedServicesFlagFg
   * Domain: Text
   * Length: 1
   * Varying Length: N
   **/
  public String InIncludeProsDestinedIndIshs1SharedServicesFlagFg;
  // Entity View: IN_INCLUDE_PROS_NOT_DESTINED_IND
  //        Type: ISHS1_SHARED_SERVICES
  /**
   * Attribute missing flag for: InIncludeProsNotDestinedIndIshs1SharedServicesFlagFg
   **/
  public char InIncludeProsNotDestinedIndIshs1SharedServicesFlagFg_AS;
  /**
   * Attribute for: InIncludeProsNotDestinedIndIshs1SharedServicesFlagFg
   * Domain: Text
   * Length: 1
   * Varying Length: N
   **/
  public String InIncludeProsNotDestinedIndIshs1SharedServicesFlagFg;
  // Entity View: IN_VALIDATE_IND
  //        Type: ISHS1_SHARED_SERVICES
  /**
   * Attribute missing flag for: InValidateIndIshs1SharedServicesFlagFg
   **/
  public char InValidateIndIshs1SharedServicesFlagFg_AS;
  /**
   * Attribute for: InValidateIndIshs1SharedServicesFlagFg
   * Domain: Text
   * Length: 1
   * Varying Length: N
   **/
  public String InValidateIndIshs1SharedServicesFlagFg;
  // Entity View: IN_DOMICILE_SIC_CD
  //        Type: ISHS1_SHARED_SERVICES
  /**
   * Attribute missing flag for: InDomicileSicCdIshs1SharedServicesString3Tx
   **/
  public char InDomicileSicCdIshs1SharedServicesString3Tx_AS;
  /**
   * Attribute for: InDomicileSicCdIshs1SharedServicesString3Tx
   * Domain: Text
   * Length: 3
   * Varying Length: N
   **/
  public String InDomicileSicCdIshs1SharedServicesString3Tx;
  // Entity View: IN_CMAN_GATEWAY_SIC
  //        Type: IOPT1_TRLR_LOAD_INST
  /**
   * Attribute missing flag for: InCmanGatewaySicIopt1TrlrLoadInstLdDest
   **/
  public char InCmanGatewaySicIopt1TrlrLoadInstLdDest_AS;
  /**
   * Attribute for: InCmanGatewaySicIopt1TrlrLoadInstLdDest
   * Domain: Text
   * Length: 3
   * Varying Length: N
   **/
  public String InCmanGatewaySicIopt1TrlrLoadInstLdDest;
  // Entity View: IN_CLOSED_TRLR_SIC_GROUP
  //        Type: IOPT1_REF_USER_SIC_GRP
  /**
   * Attribute missing flag for: InClosedTrlrSicGroupIopt1RefUserSicGrpGrpCd
   **/
  public char InClosedTrlrSicGroupIopt1RefUserSicGrpGrpCd_AS;
  /**
   * Attribute for: InClosedTrlrSicGroupIopt1RefUserSicGrpGrpCd
   * Domain: Text
   * Length: 8
   * Varying Length: N
   **/
  public String InClosedTrlrSicGroupIopt1RefUserSicGrpGrpCd;
  // Entity View: IN_INCLUDE_CLOSED_TRLR_FLAG
  //        Type: ISHS1_SHARED_SERVICES
  /**
   * Attribute missing flag for: InIncludeClosedTrlrFlagIshs1SharedServicesFlagFg
   **/
  public char InIncludeClosedTrlrFlagIshs1SharedServicesFlagFg_AS;
  /**
   * Attribute for: InIncludeClosedTrlrFlagIshs1SharedServicesFlagFg
   * Domain: Text
   * Length: 1
   * Varying Length: N
   **/
  public String InIncludeClosedTrlrFlagIshs1SharedServicesFlagFg;
  // Repeating GV:  IN_R_PRINT_GROUP
  //     Repeats: 500 times
  /**
   * Repeating group view count
   **/
  public int InRPrintGroup_MA;
  /**
   * Repeating group view occurrance array
   **/
  public char InRPrintGroup_AC[] = new char[500];
  // Entity View: IN_R_PRINT_REQUEST_KEY
  //        Type: ISHS1_SHARED_SERVICES
  /**
   * Attribute missing flag for: InRPrintRequestKeyIshs1SharedServicesString20Tx
   **/
  public char InRPrintRequestKeyIshs1SharedServicesString20Tx_AS[] = new char[500];
  /**
   * Attribute for: InRPrintRequestKeyIshs1SharedServicesString20Tx
   * Domain: Text
   * Length: 20
   * Varying Length: N
   **/
  public String InRPrintRequestKeyIshs1SharedServicesString20Tx[] = new String[500];
  // Entity View: IN_CONTROL
  //        Type: ISHS1_SHARED_SERVICES
  /**
   * Attribute missing flag for: InControlIshs1SharedServicesLongUserid
   **/
  public char InControlIshs1SharedServicesLongUserid_AS;
  /**
   * Attribute for: InControlIshs1SharedServicesLongUserid
   * Domain: Text
   * Length: 15
   * Varying Length: N
   **/
  public String InControlIshs1SharedServicesLongUserid;
  /**
   * Default Constructor
   **/
  
  public MF2AS000_IA()
  {
    reset();
  }
  /**
   * Copy Constructor
   **/
  
  public MF2AS000_IA(MF2AS000_IA orig)
  {
    copyFrom(orig);
  }
  /**
   * Static instance creator function
   **/
  
  public static MF2AS000_IA getInstance()
  {
    return new MF2AS000_IA();
  }
  /**
   * Static free instance method
   **/
  
  public void freeInstance()
  {
  }
  /**
   * clone constructor
   **/
  
  @Override public Object clone()
  	throws CloneNotSupportedException
  {
    return(new MF2AS000_IA(this));
  }
  /**
   * Resets all properties to the defaults.
   **/
  
  public void reset()
  {
    InDestSicCdIshs1SharedServicesString3Tx_AS = ' ';
    InDestSicCdIshs1SharedServicesString3Tx = "   ";
    InPrinterCodeIshs1SharedServicesString12Tx_AS = ' ';
    InPrinterCodeIshs1SharedServicesString12Tx = "            ";
    InReportTypIshs1SharedServicesString8Tx_AS = ' ';
    InReportTypIshs1SharedServicesString8Tx = "        ";
    InFormTypIshs1SharedServicesString8Tx_AS = ' ';
    InFormTypIshs1SharedServicesString8Tx = "        ";
    InReprintIndIshs1SharedServicesFlagFg_AS = ' ';
    InReprintIndIshs1SharedServicesFlagFg = " ";
    InIncludeProsDestinedIndIshs1SharedServicesFlagFg_AS = ' ';
    InIncludeProsDestinedIndIshs1SharedServicesFlagFg = " ";
    InIncludeProsNotDestinedIndIshs1SharedServicesFlagFg_AS = ' ';
    InIncludeProsNotDestinedIndIshs1SharedServicesFlagFg = " ";
    InValidateIndIshs1SharedServicesFlagFg_AS = ' ';
    InValidateIndIshs1SharedServicesFlagFg = " ";
    InDomicileSicCdIshs1SharedServicesString3Tx_AS = ' ';
    InDomicileSicCdIshs1SharedServicesString3Tx = "   ";
    InCmanGatewaySicIopt1TrlrLoadInstLdDest_AS = ' ';
    InCmanGatewaySicIopt1TrlrLoadInstLdDest = "   ";
    InClosedTrlrSicGroupIopt1RefUserSicGrpGrpCd_AS = ' ';
    InClosedTrlrSicGroupIopt1RefUserSicGrpGrpCd = "        ";
    InIncludeClosedTrlrFlagIshs1SharedServicesFlagFg_AS = ' ';
    InIncludeClosedTrlrFlagIshs1SharedServicesFlagFg = " ";
    InRPrintGroup_MA = 0;
    for(int a = 0; a < 500; a++)
    {
      InRPrintGroup_AC[a] = ' ';
      InRPrintRequestKeyIshs1SharedServicesString20Tx_AS[a] = ' ';
      InRPrintRequestKeyIshs1SharedServicesString20Tx[a] = "                    ";
    }
    InControlIshs1SharedServicesLongUserid_AS = ' ';
    InControlIshs1SharedServicesLongUserid = "               ";
  }
  /**
   * Gets the VDF array for the instance, initialized.
   **/
  
  public static VDF getViewDefinition()
  {
    if ( localVdf == null )
    {
      VDFEntry [] vdfEntries = {
        new VDFEntry((int)1, "", "InDestSicCdIshs1SharedServices", "Ishs1SharedServices", "String3Tx", VDFEntry.TYPE_STRING, (short)
          1, (short)0, 3, (short)0, null), 
        new VDFEntry((int)2, "", "InPrinterCodeIshs1SharedServices", "Ishs1SharedServices", "String12Tx", VDFEntry.TYPE_STRING, (
          short)1, (short)0, 12, (short)0, null), 
        new VDFEntry((int)3, "", "InReportTypIshs1SharedServices", "Ishs1SharedServices", "String8Tx", VDFEntry.TYPE_STRING, (short)
          1, (short)0, 8, (short)0, null), 
        new VDFEntry((int)4, "", "InFormTypIshs1SharedServices", "Ishs1SharedServices", "String8Tx", VDFEntry.TYPE_STRING, (short)1, 
          (short)0, 8, (short)0, null), 
        new VDFEntry((int)5, "", "InReprintIndIshs1SharedServices", "Ishs1SharedServices", "FlagFg", VDFEntry.TYPE_STRING, (short)1, 
          (short)0, 1, (short)0, null), 
        new VDFEntry((int)6, "", "InIncludeProsDestinedIndIshs1SharedServices", "Ishs1SharedServices", "FlagFg", 
          VDFEntry.TYPE_STRING, (short)1, (short)0, 1, (short)0, null), 
        new VDFEntry((int)7, "", "InIncludeProsNotDestinedIndIshs1SharedServices", "Ishs1SharedServices", "FlagFg", 
          VDFEntry.TYPE_STRING, (short)1, (short)0, 1, (short)0, null), 
        new VDFEntry((int)8, "", "InValidateIndIshs1SharedServices", "Ishs1SharedServices", "FlagFg", VDFEntry.TYPE_STRING, (short)1,
           (short)0, 1, (short)0, null), 
        new VDFEntry((int)9, "", "InDomicileSicCdIshs1SharedServices", "Ishs1SharedServices", "String3Tx", VDFEntry.TYPE_STRING, (
          short)1, (short)0, 3, (short)0, null), 
        new VDFEntry((int)10, "", "InCmanGatewaySicIopt1TrlrLoadInst", "Iopt1TrlrLoadInst", "LdDest", VDFEntry.TYPE_STRING, (short)1,
           (short)0, 3, (short)0, null), 
        new VDFEntry((int)11, "", "InClosedTrlrSicGroupIopt1RefUserSicGrp", "Iopt1RefUserSicGrp", "GrpCd", VDFEntry.TYPE_STRING, (
          short)1, (short)0, 8, (short)0, null), 
        new VDFEntry((int)12, "", "InIncludeClosedTrlrFlagIshs1SharedServices", "Ishs1SharedServices", "FlagFg", 
          VDFEntry.TYPE_STRING, (short)1, (short)0, 1, (short)0, null), 
        new VDFEntry((int)13, "InRPrintGroup", "", "", "MA", VDFEntry.TYPE_INT, (short)1, (short)0, 4, (short)0, null), 
        new VDFEntry((int)14, "InRPrintGroup", "", "", "AC", VDFEntry.TYPE_CHAR, (short)500, (short)0, 1, (short)0, null), 
        new VDFEntry((int)15, "InRPrintGroup", "InRPrintRequestKeyIshs1SharedServices", "Ishs1SharedServices", "String20Tx", 
          VDFEntry.TYPE_STRING, (short)500, (short)0, 20, (short)0, null), 
        new VDFEntry((int)16, "", "InControlIshs1SharedServices", "Ishs1SharedServices", "LongUserid", VDFEntry.TYPE_STRING, (short)
          1, (short)0, 15, (short)0, null), 
      };
      localVdf = new VDF(vdfEntries);
    }
    try {
      VDF result = (VDF)localVdf.clone();
      result.initViewData();
      return result;
    } catch( CloneNotSupportedException e ) {
      return null;
    }
  }
  
  /**
   * Gets the VDF version of the current state of the instance.
   **/
  public VDF getVDF()
  {
    VDF vdf = getViewDefinition();
    // predicate view item
    vdf.getEntries()[0].getDataValue().setObject(InDestSicCdIshs1SharedServicesString3Tx);
    // predicate view item
    vdf.getEntries()[1].getDataValue().setObject(InPrinterCodeIshs1SharedServicesString12Tx);
    // predicate view item
    vdf.getEntries()[2].getDataValue().setObject(InReportTypIshs1SharedServicesString8Tx);
    // predicate view item
    vdf.getEntries()[3].getDataValue().setObject(InFormTypIshs1SharedServicesString8Tx);
    // predicate view item
    vdf.getEntries()[4].getDataValue().setObject(InReprintIndIshs1SharedServicesFlagFg);
    // predicate view item
    vdf.getEntries()[5].getDataValue().setObject(InIncludeProsDestinedIndIshs1SharedServicesFlagFg);
    // predicate view item
    vdf.getEntries()[6].getDataValue().setObject(InIncludeProsNotDestinedIndIshs1SharedServicesFlagFg);
    // predicate view item
    vdf.getEntries()[7].getDataValue().setObject(InValidateIndIshs1SharedServicesFlagFg);
    // predicate view item
    vdf.getEntries()[8].getDataValue().setObject(InDomicileSicCdIshs1SharedServicesString3Tx);
    // predicate view item
    vdf.getEntries()[9].getDataValue().setObject(InCmanGatewaySicIopt1TrlrLoadInstLdDest);
    // predicate view item
    vdf.getEntries()[10].getDataValue().setObject(InClosedTrlrSicGroupIopt1RefUserSicGrpGrpCd);
    // predicate view item
    vdf.getEntries()[11].getDataValue().setObject(InIncludeClosedTrlrFlagIshs1SharedServicesFlagFg);
    // group view current cardinality
    vdf.getEntries()[12].getDataValue().setObject(new Integer(InRPrintGroup_MA));
    // group view active flags
    for(int adim0 = 0; adim0 < 500; adim0++)
    {
      if ( adim0 < InRPrintGroup_MA )
      {
        ((VDFEntryObject [])vdf.getEntries()[13].getDataValue().getObject())[adim0].setObject(new Character('Y'));
      }
      else 
      {
        ((VDFEntryObject [])vdf.getEntries()[13].getDataValue().getObject())[adim0].setObject(new Character('N'));
      }
    }
    vdf.getEntries()[13].setCountUsed((short)InRPrintGroup_MA);
    // current cardinality group view items
    for(int adim0 = 0; adim0 < 500; adim0++)
    {
      ((VDFEntryObject [])vdf.getEntries()[14].getDataValue().getObject())[adim0].setObject(
        InRPrintRequestKeyIshs1SharedServicesString20Tx[adim0]);
    }
    vdf.getEntries()[14].setCountUsed((short)InRPrintGroup_MA);
    // predicate view item
    vdf.getEntries()[15].getDataValue().setObject(InControlIshs1SharedServicesLongUserid);
    return(vdf);
  }
  
  /**
   * Sets the current state of the instance to the VDF version.
   **/
  public void setFromVDF(VDF vdf)
  {
    // predicate view item
    if ( vdf.getEntries()[0].getDataValue().getObject() != null )
    {
      InDestSicCdIshs1SharedServicesString3Tx = ((String)vdf.getEntries()[0].getDataValue().getObject());
    }
    else 
    {
      InDestSicCdIshs1SharedServicesString3Tx = "   ";
    }
    // predicate view item
    if ( vdf.getEntries()[1].getDataValue().getObject() != null )
    {
      InPrinterCodeIshs1SharedServicesString12Tx = ((String)vdf.getEntries()[1].getDataValue().getObject());
    }
    else 
    {
      InPrinterCodeIshs1SharedServicesString12Tx = "            ";
    }
    // predicate view item
    if ( vdf.getEntries()[2].getDataValue().getObject() != null )
    {
      InReportTypIshs1SharedServicesString8Tx = ((String)vdf.getEntries()[2].getDataValue().getObject());
    }
    else 
    {
      InReportTypIshs1SharedServicesString8Tx = "        ";
    }
    // predicate view item
    if ( vdf.getEntries()[3].getDataValue().getObject() != null )
    {
      InFormTypIshs1SharedServicesString8Tx = ((String)vdf.getEntries()[3].getDataValue().getObject());
    }
    else 
    {
      InFormTypIshs1SharedServicesString8Tx = "        ";
    }
    // predicate view item
    if ( vdf.getEntries()[4].getDataValue().getObject() != null )
    {
      InReprintIndIshs1SharedServicesFlagFg = ((String)vdf.getEntries()[4].getDataValue().getObject());
    }
    else 
    {
      InReprintIndIshs1SharedServicesFlagFg = " ";
    }
    // predicate view item
    if ( vdf.getEntries()[5].getDataValue().getObject() != null )
    {
      InIncludeProsDestinedIndIshs1SharedServicesFlagFg = ((String)vdf.getEntries()[5].getDataValue().getObject());
    }
    else 
    {
      InIncludeProsDestinedIndIshs1SharedServicesFlagFg = " ";
    }
    // predicate view item
    if ( vdf.getEntries()[6].getDataValue().getObject() != null )
    {
      InIncludeProsNotDestinedIndIshs1SharedServicesFlagFg = ((String)vdf.getEntries()[6].getDataValue().getObject());
    }
    else 
    {
      InIncludeProsNotDestinedIndIshs1SharedServicesFlagFg = " ";
    }
    // predicate view item
    if ( vdf.getEntries()[7].getDataValue().getObject() != null )
    {
      InValidateIndIshs1SharedServicesFlagFg = ((String)vdf.getEntries()[7].getDataValue().getObject());
    }
    else 
    {
      InValidateIndIshs1SharedServicesFlagFg = " ";
    }
    // predicate view item
    if ( vdf.getEntries()[8].getDataValue().getObject() != null )
    {
      InDomicileSicCdIshs1SharedServicesString3Tx = ((String)vdf.getEntries()[8].getDataValue().getObject());
    }
    else 
    {
      InDomicileSicCdIshs1SharedServicesString3Tx = "   ";
    }
    // predicate view item
    if ( vdf.getEntries()[9].getDataValue().getObject() != null )
    {
      InCmanGatewaySicIopt1TrlrLoadInstLdDest = ((String)vdf.getEntries()[9].getDataValue().getObject());
    }
    else 
    {
      InCmanGatewaySicIopt1TrlrLoadInstLdDest = "   ";
    }
    // predicate view item
    if ( vdf.getEntries()[10].getDataValue().getObject() != null )
    {
      InClosedTrlrSicGroupIopt1RefUserSicGrpGrpCd = ((String)vdf.getEntries()[10].getDataValue().getObject());
    }
    else 
    {
      InClosedTrlrSicGroupIopt1RefUserSicGrpGrpCd = "        ";
    }
    // predicate view item
    if ( vdf.getEntries()[11].getDataValue().getObject() != null )
    {
      InIncludeClosedTrlrFlagIshs1SharedServicesFlagFg = ((String)vdf.getEntries()[11].getDataValue().getObject());
    }
    else 
    {
      InIncludeClosedTrlrFlagIshs1SharedServicesFlagFg = " ";
    }
    // group view current cardinality
    if ( vdf.getEntries()[12].getDataValue().getObject() != null )
    {
      InRPrintGroup_MA = ((Integer)vdf.getEntries()[12].getDataValue().getObject()).intValue();
    }
    else 
    {
      InRPrintGroup_MA = 0;
    }
    // group view active flags
    for(int adim0 = 0; adim0 < InRPrintGroup_MA; adim0++)
    {
      if ( ((VDFEntryObject [])vdf.getEntries()[13].getDataValue().getObject())[adim0].getObject() != null )
      {
        InRPrintGroup_AC[adim0] = ((Character)((VDFEntryObject [])vdf.getEntries()[13].getDataValue().getObject())[adim0].getObject()
          ).charValue();
      }
      else 
      {
        InRPrintGroup_AC[adim0] = ' ';
      }
    }
    // current cardinality group view items
    for(int adim0 = 0; adim0 < InRPrintGroup_MA; adim0++)
    {
      if ( ((VDFEntryObject [])vdf.getEntries()[14].getDataValue().getObject())[adim0].getObject() != null )
      {
        InRPrintRequestKeyIshs1SharedServicesString20Tx[adim0] = ((String)((VDFEntryObject [])vdf.getEntries()[14].getDataValue()
          .getObject())[adim0].getObject());
      }
      else 
      {
        InRPrintRequestKeyIshs1SharedServicesString20Tx[adim0] = "                    ";
      }
    }
    // predicate view item
    if ( vdf.getEntries()[15].getDataValue().getObject() != null )
    {
      InControlIshs1SharedServicesLongUserid = ((String)vdf.getEntries()[15].getDataValue().getObject());
    }
    else 
    {
      InControlIshs1SharedServicesLongUserid = "               ";
    }
  }
  
  /**
   * Sets the current instance based on the passed view.
   **/
  public void copyFrom(IImportView orig)
  {
    this.copyFrom((MF2AS000_IA) orig);
  }
  
  /**
   * Sets the current instance based on the passed view.
   **/
  public void copyFrom(MF2AS000_IA orig)
  {
    InDestSicCdIshs1SharedServicesString3Tx_AS = orig.InDestSicCdIshs1SharedServicesString3Tx_AS;
    InDestSicCdIshs1SharedServicesString3Tx = orig.InDestSicCdIshs1SharedServicesString3Tx;
    InPrinterCodeIshs1SharedServicesString12Tx_AS = orig.InPrinterCodeIshs1SharedServicesString12Tx_AS;
    InPrinterCodeIshs1SharedServicesString12Tx = orig.InPrinterCodeIshs1SharedServicesString12Tx;
    InReportTypIshs1SharedServicesString8Tx_AS = orig.InReportTypIshs1SharedServicesString8Tx_AS;
    InReportTypIshs1SharedServicesString8Tx = orig.InReportTypIshs1SharedServicesString8Tx;
    InFormTypIshs1SharedServicesString8Tx_AS = orig.InFormTypIshs1SharedServicesString8Tx_AS;
    InFormTypIshs1SharedServicesString8Tx = orig.InFormTypIshs1SharedServicesString8Tx;
    InReprintIndIshs1SharedServicesFlagFg_AS = orig.InReprintIndIshs1SharedServicesFlagFg_AS;
    InReprintIndIshs1SharedServicesFlagFg = orig.InReprintIndIshs1SharedServicesFlagFg;
    InIncludeProsDestinedIndIshs1SharedServicesFlagFg_AS = orig.InIncludeProsDestinedIndIshs1SharedServicesFlagFg_AS;
    InIncludeProsDestinedIndIshs1SharedServicesFlagFg = orig.InIncludeProsDestinedIndIshs1SharedServicesFlagFg;
    InIncludeProsNotDestinedIndIshs1SharedServicesFlagFg_AS = orig.InIncludeProsNotDestinedIndIshs1SharedServicesFlagFg_AS;
    InIncludeProsNotDestinedIndIshs1SharedServicesFlagFg = orig.InIncludeProsNotDestinedIndIshs1SharedServicesFlagFg;
    InValidateIndIshs1SharedServicesFlagFg_AS = orig.InValidateIndIshs1SharedServicesFlagFg_AS;
    InValidateIndIshs1SharedServicesFlagFg = orig.InValidateIndIshs1SharedServicesFlagFg;
    InDomicileSicCdIshs1SharedServicesString3Tx_AS = orig.InDomicileSicCdIshs1SharedServicesString3Tx_AS;
    InDomicileSicCdIshs1SharedServicesString3Tx = orig.InDomicileSicCdIshs1SharedServicesString3Tx;
    InCmanGatewaySicIopt1TrlrLoadInstLdDest_AS = orig.InCmanGatewaySicIopt1TrlrLoadInstLdDest_AS;
    InCmanGatewaySicIopt1TrlrLoadInstLdDest = orig.InCmanGatewaySicIopt1TrlrLoadInstLdDest;
    InClosedTrlrSicGroupIopt1RefUserSicGrpGrpCd_AS = orig.InClosedTrlrSicGroupIopt1RefUserSicGrpGrpCd_AS;
    InClosedTrlrSicGroupIopt1RefUserSicGrpGrpCd = orig.InClosedTrlrSicGroupIopt1RefUserSicGrpGrpCd;
    InIncludeClosedTrlrFlagIshs1SharedServicesFlagFg_AS = orig.InIncludeClosedTrlrFlagIshs1SharedServicesFlagFg_AS;
    InIncludeClosedTrlrFlagIshs1SharedServicesFlagFg = orig.InIncludeClosedTrlrFlagIshs1SharedServicesFlagFg;
    InRPrintGroup_MA = orig.InRPrintGroup_MA;
    for(int a = 0; a < 500; a++)
    {
      InRPrintGroup_AC[a] = orig.InRPrintGroup_AC[a];
      InRPrintRequestKeyIshs1SharedServicesString20Tx_AS[a] = orig.InRPrintRequestKeyIshs1SharedServicesString20Tx_AS[a];
      InRPrintRequestKeyIshs1SharedServicesString20Tx[a] = orig.InRPrintRequestKeyIshs1SharedServicesString20Tx[a];
    }
    InControlIshs1SharedServicesLongUserid_AS = orig.InControlIshs1SharedServicesLongUserid_AS;
    InControlIshs1SharedServicesLongUserid = orig.InControlIshs1SharedServicesLongUserid;
  }
}
