package proxy.mfl.io;
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
//
//                    Source Code Generated by
//                           CA Gen 8.5
//
//    Copyright (c) 2016 CA Technologies. All rights reserved.
//
//    Name: MF2AS000_OA                      Date: 2016/09/15
//    User: djrichard                        Time: 08:48:22
//
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
// Import Statements
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
import java.lang.*;
import java.io.*;
import java.util.*;
import java.math.*;
import java.sql.*;
import com.ca.gen85.vwrt.*;
import com.ca.gen85.vwrt.types.*;
import com.ca.gen85.vwrt.vdf.*;
import com.ca.gen85.csu.exception.*;

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
// START OF EXPORT VIEW
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
/**
 * Internal data view storage for: MF2AS000_OA
 **/
public class MF2AS000_OA extends ViewBase implements IExportView, Serializable
{
  static VDF localVdf = null;
  
  // Entity View: OUT_FORM_TYPE_LOADED
  //        Type: IRTR1_PRINTER
  /**
   * Attribute missing flag for: OutFormTypeLoadedIrtr1PrinterFormTyp
   **/
  public char OutFormTypeLoadedIrtr1PrinterFormTyp_AS;
  /**
   * Dynamic attribute for: OutFormTypeLoadedIrtr1PrinterFormTyp
   **/
  public DynamicAttr OutFormTypeLoadedIrtr1PrinterFormTyp_AT;
  /**
   * Attribute for: OutFormTypeLoadedIrtr1PrinterFormTyp
   * Domain: Text
   * Length: 8
   * Varying Length: N
   **/
  public String OutFormTypeLoadedIrtr1PrinterFormTyp;
  // Entity View: OUT_VALUE_IN_ERROR
  //        Type: ISHS1_SHARED_SERVICES
  /**
   * Attribute missing flag for: OutValueInErrorIshs1SharedServicesString20Tx
   **/
  public char OutValueInErrorIshs1SharedServicesString20Tx_AS;
  /**
   * Dynamic attribute for: OutValueInErrorIshs1SharedServicesString20Tx
   **/
  public DynamicAttr OutValueInErrorIshs1SharedServicesString20Tx_AT;
  /**
   * Attribute for: OutValueInErrorIshs1SharedServicesString20Tx
   * Domain: Text
   * Length: 20
   * Varying Length: N
   **/
  public String OutValueInErrorIshs1SharedServicesString20Tx;
  // Entity View: OUT_ERROR
  //        Type: ISHS1_SHARED_SERVICES
  /**
   * Attribute missing flag for: OutErrorIshs1SharedServicesReasonCd
   **/
  public char OutErrorIshs1SharedServicesReasonCd_AS;
  /**
   * Dynamic attribute for: OutErrorIshs1SharedServicesReasonCd
   **/
  public DynamicAttr OutErrorIshs1SharedServicesReasonCd_AT;
  /**
   * Attribute for: OutErrorIshs1SharedServicesReasonCd
   * Domain: Number
   * Length: 5
   * Decimal Places: 0
   * Decimal Precision: N
   **/
  public int OutErrorIshs1SharedServicesReasonCd;
  /**
   * Attribute missing flag for: OutErrorIshs1SharedServicesReturnCd
   **/
  public char OutErrorIshs1SharedServicesReturnCd_AS;
  /**
   * Dynamic attribute for: OutErrorIshs1SharedServicesReturnCd
   **/
  public DynamicAttr OutErrorIshs1SharedServicesReturnCd_AT;
  /**
   * Attribute for: OutErrorIshs1SharedServicesReturnCd
   * Domain: Number
   * Length: 5
   * Decimal Places: 0
   * Decimal Precision: N
   **/
  public int OutErrorIshs1SharedServicesReturnCd;
  /**
   * Attribute missing flag for: OutErrorIshs1SharedServicesContextStringTx
   **/
  public char OutErrorIshs1SharedServicesContextStringTx_AS;
  /**
   * Dynamic attribute for: OutErrorIshs1SharedServicesContextStringTx
   **/
  public DynamicAttr OutErrorIshs1SharedServicesContextStringTx_AT;
  /**
   * Attribute for: OutErrorIshs1SharedServicesContextStringTx
   * Domain: Text
   * Length: 255
   * Varying Length: Y
   **/
  public String OutErrorIshs1SharedServicesContextStringTx;
  /**
   * Attribute missing flag for: OutErrorIshs1SharedServicesSubscriptNb
   **/
  public char OutErrorIshs1SharedServicesSubscriptNb_AS;
  /**
   * Dynamic attribute for: OutErrorIshs1SharedServicesSubscriptNb
   **/
  public DynamicAttr OutErrorIshs1SharedServicesSubscriptNb_AT;
  /**
   * Attribute for: OutErrorIshs1SharedServicesSubscriptNb
   * Domain: Number
   * Length: 9
   * Decimal Places: 0
   * Decimal Precision: N
   **/
  public int OutErrorIshs1SharedServicesSubscriptNb;
  /**
   * Attribute missing flag for: OutErrorIshs1SharedServicesOriginServerId
   **/
  public char OutErrorIshs1SharedServicesOriginServerId_AS;
  /**
   * Dynamic attribute for: OutErrorIshs1SharedServicesOriginServerId
   **/
  public DynamicAttr OutErrorIshs1SharedServicesOriginServerId_AT;
  /**
   * Attribute for: OutErrorIshs1SharedServicesOriginServerId
   * Domain: Number
   * Length: 15
   * Decimal Places: 0
   * Decimal Precision: N
   **/
  public double OutErrorIshs1SharedServicesOriginServerId;
  /**
   * Default Constructor
   **/
  
  public MF2AS000_OA()
  {
    reset();
  }
  /**
   * Copy Constructor
   **/
  
  public MF2AS000_OA(MF2AS000_OA orig)
  {
    copyFrom(orig);
  }
  /**
   * Static instance creator function
   **/
  
  public static MF2AS000_OA getInstance()
  {
    return new MF2AS000_OA();
  }
  /**
   * Static free instance method
   **/
  
  public void freeInstance()
  {
  }
  /**
   * clone constructor
   **/
  
  @Override public Object clone()
  	throws CloneNotSupportedException
  {
    return(new MF2AS000_OA(this));
  }
  /**
   * Resets all properties to the defaults.
   **/
  
  public void reset()
  {
    OutFormTypeLoadedIrtr1PrinterFormTyp_AT = null;
    OutFormTypeLoadedIrtr1PrinterFormTyp_AS = ' ';
    OutFormTypeLoadedIrtr1PrinterFormTyp = "        ";
    OutValueInErrorIshs1SharedServicesString20Tx_AT = null;
    OutValueInErrorIshs1SharedServicesString20Tx_AS = ' ';
    OutValueInErrorIshs1SharedServicesString20Tx = "                    ";
    OutErrorIshs1SharedServicesReasonCd_AT = null;
    OutErrorIshs1SharedServicesReasonCd_AS = ' ';
    OutErrorIshs1SharedServicesReasonCd = 0;
    OutErrorIshs1SharedServicesReturnCd_AT = null;
    OutErrorIshs1SharedServicesReturnCd_AS = ' ';
    OutErrorIshs1SharedServicesReturnCd = 0;
    OutErrorIshs1SharedServicesContextStringTx_AT = null;
    OutErrorIshs1SharedServicesContextStringTx_AS = ' ';
    OutErrorIshs1SharedServicesContextStringTx = "";
    OutErrorIshs1SharedServicesSubscriptNb_AT = null;
    OutErrorIshs1SharedServicesSubscriptNb_AS = ' ';
    OutErrorIshs1SharedServicesSubscriptNb = 0;
    OutErrorIshs1SharedServicesOriginServerId_AT = null;
    OutErrorIshs1SharedServicesOriginServerId_AS = ' ';
    OutErrorIshs1SharedServicesOriginServerId = 0.0;
  }
  /**
   * Gets the VDF array for the instance, initialized.
   **/
  
  public static VDF getViewDefinition()
  {
    if ( localVdf == null )
    {
      VDFEntry [] vdfEntries = {
        new VDFEntry((int)1, "", "OutFormTypeLoadedIrtr1Printer", "Irtr1Printer", "FormTyp", VDFEntry.TYPE_STRING, (short)1, (short)
          0, 8, (short)0, null), 
        new VDFEntry((int)2, "", "OutValueInErrorIshs1SharedServices", "Ishs1SharedServices", "String20Tx", VDFEntry.TYPE_STRING, (
          short)1, (short)0, 20, (short)0, null), 
        new VDFEntry((int)3, "", "OutErrorIshs1SharedServices", "Ishs1SharedServices", "ReasonCd", VDFEntry.TYPE_INT, (short)1, (
          short)0, 8, (short)0, null), 
        new VDFEntry((int)4, "", "OutErrorIshs1SharedServices", "Ishs1SharedServices", "ReturnCd", VDFEntry.TYPE_INT, (short)1, (
          short)0, 8, (short)0, null), 
        new VDFEntry((int)5, "", "OutErrorIshs1SharedServices", "Ishs1SharedServices", "ContextStringTx", VDFEntry.TYPE_STRING, (
          short)1, (short)0, 255, (short)0, null), 
        new VDFEntry((int)6, "", "OutErrorIshs1SharedServices", "Ishs1SharedServices", "SubscriptNb", VDFEntry.TYPE_INT, (short)1, (
          short)0, 8, (short)0, null), 
        new VDFEntry((int)7, "", "OutErrorIshs1SharedServices", "Ishs1SharedServices", "OriginServerId", VDFEntry.TYPE_DOUBLE, (
          short)1, (short)0, 15, (short)0, null), 
      };
      localVdf = new VDF(vdfEntries);
    }
    try {
      VDF result = (VDF)localVdf.clone();
      result.initViewData();
      return result;
    } catch( CloneNotSupportedException e ) {
      return null;
    }
  }
  
  /**
   * Sets the current state of the instance to the VDF version.
   **/
  public void setFromVDF(VDF vdf)
  {
    // predicate view item
    if ( vdf.getEntries()[0].getDataValue().getObject() != null )
    {
      OutFormTypeLoadedIrtr1PrinterFormTyp = ((String)vdf.getEntries()[0].getDataValue().getObject());
    }
    else 
    {
      OutFormTypeLoadedIrtr1PrinterFormTyp = "        ";
    }
    // predicate view item
    if ( vdf.getEntries()[1].getDataValue().getObject() != null )
    {
      OutValueInErrorIshs1SharedServicesString20Tx = ((String)vdf.getEntries()[1].getDataValue().getObject());
    }
    else 
    {
      OutValueInErrorIshs1SharedServicesString20Tx = "                    ";
    }
    // predicate view item
    if ( vdf.getEntries()[2].getDataValue().getObject() != null )
    {
      OutErrorIshs1SharedServicesReasonCd = ((Integer)vdf.getEntries()[2].getDataValue().getObject()).intValue();
    }
    else 
    {
      OutErrorIshs1SharedServicesReasonCd = 0;
    }
    // predicate view item
    if ( vdf.getEntries()[3].getDataValue().getObject() != null )
    {
      OutErrorIshs1SharedServicesReturnCd = ((Integer)vdf.getEntries()[3].getDataValue().getObject()).intValue();
    }
    else 
    {
      OutErrorIshs1SharedServicesReturnCd = 0;
    }
    // predicate view item
    if ( vdf.getEntries()[4].getDataValue().getObject() != null )
    {
      OutErrorIshs1SharedServicesContextStringTx = ((String)vdf.getEntries()[4].getDataValue().getObject());
    }
    else 
    {
      OutErrorIshs1SharedServicesContextStringTx = "";
    }
    // predicate view item
    if ( vdf.getEntries()[5].getDataValue().getObject() != null )
    {
      OutErrorIshs1SharedServicesSubscriptNb = ((Integer)vdf.getEntries()[5].getDataValue().getObject()).intValue();
    }
    else 
    {
      OutErrorIshs1SharedServicesSubscriptNb = 0;
    }
    // predicate view item
    if ( vdf.getEntries()[6].getDataValue().getObject() != null )
    {
      OutErrorIshs1SharedServicesOriginServerId = ((Double)vdf.getEntries()[6].getDataValue().getObject()).doubleValue();
    }
    else 
    {
      OutErrorIshs1SharedServicesOriginServerId = 0.0;
    }
  }
  
  /**
   * Gets the VDF version of the current state of the instance.
   **/
  public VDF getVDF()
  {
    VDF vdf = getViewDefinition();
    // predicate view item
    vdf.getEntries()[0].getDataValue().setObject(OutFormTypeLoadedIrtr1PrinterFormTyp);
    // predicate view item
    vdf.getEntries()[1].getDataValue().setObject(OutValueInErrorIshs1SharedServicesString20Tx);
    // predicate view item
    vdf.getEntries()[2].getDataValue().setObject(new Integer(OutErrorIshs1SharedServicesReasonCd));
    // predicate view item
    vdf.getEntries()[3].getDataValue().setObject(new Integer(OutErrorIshs1SharedServicesReturnCd));
    // predicate view item
    vdf.getEntries()[4].getDataValue().setObject(OutErrorIshs1SharedServicesContextStringTx);
    // predicate view item
    vdf.getEntries()[5].getDataValue().setObject(new Integer(OutErrorIshs1SharedServicesSubscriptNb));
    // predicate view item
    vdf.getEntries()[6].getDataValue().setObject(new Double(OutErrorIshs1SharedServicesOriginServerId));
    return(vdf);
  }
  
  /**
   * Sets the current instance based on the passed view.
   **/
  public void copyFrom(IExportView orig)
  {
    this.copyFrom((MF2AS000_OA) orig);
  }
  
  /**
   * Sets the current instance based on the passed view.
   **/
  public void copyFrom(MF2AS000_OA orig)
  {
    OutFormTypeLoadedIrtr1PrinterFormTyp_AT = orig.OutFormTypeLoadedIrtr1PrinterFormTyp_AT;
    OutFormTypeLoadedIrtr1PrinterFormTyp_AS = orig.OutFormTypeLoadedIrtr1PrinterFormTyp_AS;
    OutFormTypeLoadedIrtr1PrinterFormTyp = orig.OutFormTypeLoadedIrtr1PrinterFormTyp;
    OutValueInErrorIshs1SharedServicesString20Tx_AT = orig.OutValueInErrorIshs1SharedServicesString20Tx_AT;
    OutValueInErrorIshs1SharedServicesString20Tx_AS = orig.OutValueInErrorIshs1SharedServicesString20Tx_AS;
    OutValueInErrorIshs1SharedServicesString20Tx = orig.OutValueInErrorIshs1SharedServicesString20Tx;
    OutErrorIshs1SharedServicesReasonCd_AT = orig.OutErrorIshs1SharedServicesReasonCd_AT;
    OutErrorIshs1SharedServicesReasonCd_AS = orig.OutErrorIshs1SharedServicesReasonCd_AS;
    OutErrorIshs1SharedServicesReasonCd = orig.OutErrorIshs1SharedServicesReasonCd;
    OutErrorIshs1SharedServicesReturnCd_AT = orig.OutErrorIshs1SharedServicesReturnCd_AT;
    OutErrorIshs1SharedServicesReturnCd_AS = orig.OutErrorIshs1SharedServicesReturnCd_AS;
    OutErrorIshs1SharedServicesReturnCd = orig.OutErrorIshs1SharedServicesReturnCd;
    OutErrorIshs1SharedServicesContextStringTx_AT = orig.OutErrorIshs1SharedServicesContextStringTx_AT;
    OutErrorIshs1SharedServicesContextStringTx_AS = orig.OutErrorIshs1SharedServicesContextStringTx_AS;
    OutErrorIshs1SharedServicesContextStringTx = orig.OutErrorIshs1SharedServicesContextStringTx;
    OutErrorIshs1SharedServicesSubscriptNb_AT = orig.OutErrorIshs1SharedServicesSubscriptNb_AT;
    OutErrorIshs1SharedServicesSubscriptNb_AS = orig.OutErrorIshs1SharedServicesSubscriptNb_AS;
    OutErrorIshs1SharedServicesSubscriptNb = orig.OutErrorIshs1SharedServicesSubscriptNb;
    OutErrorIshs1SharedServicesOriginServerId_AT = orig.OutErrorIshs1SharedServicesOriginServerId_AT;
    OutErrorIshs1SharedServicesOriginServerId_AS = orig.OutErrorIshs1SharedServicesOriginServerId_AS;
    OutErrorIshs1SharedServicesOriginServerId = orig.OutErrorIshs1SharedServicesOriginServerId;
  }
}
