package proxy.bol.io;
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
//
//                    Source Code Generated by
//                           CA Gen 8.6
//
//    Copyright (c) 2021 CA Technologies. All rights reserved.
//
//    Name: BO11S000_OA                      Date: 2021/01/07
//    User: sehgal.suneet                    Time: 21:18:18
//
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
// Import Statements
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
import java.lang.*;
import java.io.*;
import java.util.*;
import java.math.*;
import java.sql.*;
import com.ca.gen.vwrt.*;
import com.ca.gen.vwrt.types.*;
import com.ca.gen.vwrt.vdf.*;
import com.ca.gen.csu.exception.*;

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
// START OF EXPORT VIEW
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
/**
 * Internal data view storage for: BO11S000_OA
 **/
public class BO11S000_OA extends ViewBase implements IExportView, Serializable
{
  static VDF localVdf = null;
  
  // Repeating GV:  OUT_GROUP_DOC_HANDLING_UNITS
  //     Repeats: 200 times
  /**
   * Repeating group view count
   **/
  public int OutGroupDocHandlingUnits_MA;
  /**
   * Repeating group view occurrance array
   **/
  public char OutGroupDocHandlingUnits_AC[] = new char[200];
  // Entity View: OUT_GRP_DOC_HANDLING_UNIT
  //        Type: IBOL1_DOC_HANDLING_UNIT
  /**
   * Attribute missing flag for: OutGrpDocHandlingUnitIbol1DocHandlingUnitChildProNbrTxt
   **/
  public char OutGrpDocHandlingUnitIbol1DocHandlingUnitChildProNbrTxt_AS[] = new char[200];
  /**
   * Dynamic attribute for: OutGrpDocHandlingUnitIbol1DocHandlingUnitChildProNbrTxt
   **/
  public DynamicAttr OutGrpDocHandlingUnitIbol1DocHandlingUnitChildProNbrTxt_AT[] = new DynamicAttr[200];
  /**
   * Attribute for: OutGrpDocHandlingUnitIbol1DocHandlingUnitChildProNbrTxt
   * Domain: Text
   * Length: 11
   * Varying Length: N
   **/
  public String OutGrpDocHandlingUnitIbol1DocHandlingUnitChildProNbrTxt[] = new String[200];
  /**
   * Attribute missing flag for: OutGrpDocHandlingUnitIbol1DocHandlingUnitBolInstId
   **/
  public char OutGrpDocHandlingUnitIbol1DocHandlingUnitBolInstId_AS[] = new char[200];
  /**
   * Dynamic attribute for: OutGrpDocHandlingUnitIbol1DocHandlingUnitBolInstId
   **/
  public DynamicAttr OutGrpDocHandlingUnitIbol1DocHandlingUnitBolInstId_AT[] = new DynamicAttr[200];
  /**
   * Attribute for: OutGrpDocHandlingUnitIbol1DocHandlingUnitBolInstId
   * Domain: Number
   * Length: 15
   * Decimal Places: 0
   * Decimal Precision: N
   **/
  public double OutGrpDocHandlingUnitIbol1DocHandlingUnitBolInstId[] = new double[200];
  /**
   * Attribute missing flag for: OutGrpDocHandlingUnitIbol1DocHandlingUnitSeqNbr
   **/
  public char OutGrpDocHandlingUnitIbol1DocHandlingUnitSeqNbr_AS[] = new char[200];
  /**
   * Dynamic attribute for: OutGrpDocHandlingUnitIbol1DocHandlingUnitSeqNbr
   **/
  public DynamicAttr OutGrpDocHandlingUnitIbol1DocHandlingUnitSeqNbr_AT[] = new DynamicAttr[200];
  /**
   * Attribute for: OutGrpDocHandlingUnitIbol1DocHandlingUnitSeqNbr
   * Domain: Number
   * Length: 4
   * Decimal Places: 0
   * Decimal Precision: N
   **/
  public short OutGrpDocHandlingUnitIbol1DocHandlingUnitSeqNbr[] = new short[200];
  /**
   * Attribute missing flag for: OutGrpDocHandlingUnitIbol1DocHandlingUnitCreateDt
   **/
  public char OutGrpDocHandlingUnitIbol1DocHandlingUnitCreateDt_AS[] = new char[200];
  /**
   * Dynamic attribute for: OutGrpDocHandlingUnitIbol1DocHandlingUnitCreateDt
   **/
  public DynamicAttr OutGrpDocHandlingUnitIbol1DocHandlingUnitCreateDt_AT[] = new DynamicAttr[200];
  /**
   * Attribute for: OutGrpDocHandlingUnitIbol1DocHandlingUnitCreateDt
   * Domain: Date
   * Length: 8
   **/
  public int OutGrpDocHandlingUnitIbol1DocHandlingUnitCreateDt[] = new int[200];
  // Entity View: OUT_ERROR
  //        Type: ISHS1_SHARED_SERVICES
  /**
   * Attribute missing flag for: OutErrorIshs1SharedServicesDataStoreStatusCd
   **/
  public char OutErrorIshs1SharedServicesDataStoreStatusCd_AS;
  /**
   * Dynamic attribute for: OutErrorIshs1SharedServicesDataStoreStatusCd
   **/
  public DynamicAttr OutErrorIshs1SharedServicesDataStoreStatusCd_AT;
  /**
   * Attribute for: OutErrorIshs1SharedServicesDataStoreStatusCd
   * Domain: Text
   * Length: 1
   * Varying Length: N
   **/
  public String OutErrorIshs1SharedServicesDataStoreStatusCd;
  /**
   * Attribute missing flag for: OutErrorIshs1SharedServicesOriginServerId
   **/
  public char OutErrorIshs1SharedServicesOriginServerId_AS;
  /**
   * Dynamic attribute for: OutErrorIshs1SharedServicesOriginServerId
   **/
  public DynamicAttr OutErrorIshs1SharedServicesOriginServerId_AT;
  /**
   * Attribute for: OutErrorIshs1SharedServicesOriginServerId
   * Domain: Number
   * Length: 15
   * Decimal Places: 0
   * Decimal Precision: N
   **/
  public double OutErrorIshs1SharedServicesOriginServerId;
  /**
   * Attribute missing flag for: OutErrorIshs1SharedServicesContextStringTx
   **/
  public char OutErrorIshs1SharedServicesContextStringTx_AS;
  /**
   * Dynamic attribute for: OutErrorIshs1SharedServicesContextStringTx
   **/
  public DynamicAttr OutErrorIshs1SharedServicesContextStringTx_AT;
  /**
   * Attribute for: OutErrorIshs1SharedServicesContextStringTx
   * Domain: Text
   * Length: 255
   * Varying Length: Y
   **/
  public String OutErrorIshs1SharedServicesContextStringTx;
  /**
   * Attribute missing flag for: OutErrorIshs1SharedServicesReturnCd
   **/
  public char OutErrorIshs1SharedServicesReturnCd_AS;
  /**
   * Dynamic attribute for: OutErrorIshs1SharedServicesReturnCd
   **/
  public DynamicAttr OutErrorIshs1SharedServicesReturnCd_AT;
  /**
   * Attribute for: OutErrorIshs1SharedServicesReturnCd
   * Domain: Number
   * Length: 5
   * Decimal Places: 0
   * Decimal Precision: N
   **/
  public int OutErrorIshs1SharedServicesReturnCd;
  /**
   * Attribute missing flag for: OutErrorIshs1SharedServicesReasonCd
   **/
  public char OutErrorIshs1SharedServicesReasonCd_AS;
  /**
   * Dynamic attribute for: OutErrorIshs1SharedServicesReasonCd
   **/
  public DynamicAttr OutErrorIshs1SharedServicesReasonCd_AT;
  /**
   * Attribute for: OutErrorIshs1SharedServicesReasonCd
   * Domain: Number
   * Length: 5
   * Decimal Places: 0
   * Decimal Precision: N
   **/
  public int OutErrorIshs1SharedServicesReasonCd;
  /**
   * Default Constructor
   **/
  
  public BO11S000_OA()
  {
    reset();
  }
  /**
   * Copy Constructor
   **/
  
  public BO11S000_OA(BO11S000_OA orig)
  {
    copyFrom(orig);
  }
  /**
   * Static instance creator function
   **/
  
  public static BO11S000_OA getInstance()
  {
    return new BO11S000_OA();
  }
  /**
   * Static free instance method
   **/
  
  public void freeInstance()
  {
  }
  /**
   * clone constructor
   **/
  
  @Override public Object clone()
  	throws CloneNotSupportedException
  {
    return(new BO11S000_OA(this));
  }
  /**
   * Resets all properties to the defaults.
   **/
  
  public void reset()
  {
    OutGroupDocHandlingUnits_MA = 0;
    for(int a = 0; a < 200; a++)
    {
      OutGroupDocHandlingUnits_AC[a] = ' ';
      OutGrpDocHandlingUnitIbol1DocHandlingUnitChildProNbrTxt_AT[a] = null;
      OutGrpDocHandlingUnitIbol1DocHandlingUnitChildProNbrTxt_AS[a] = ' ';
      OutGrpDocHandlingUnitIbol1DocHandlingUnitChildProNbrTxt[a] = "           ";
      OutGrpDocHandlingUnitIbol1DocHandlingUnitBolInstId_AT[a] = null;
      OutGrpDocHandlingUnitIbol1DocHandlingUnitBolInstId_AS[a] = ' ';
      OutGrpDocHandlingUnitIbol1DocHandlingUnitBolInstId[a] = 0.0;
      OutGrpDocHandlingUnitIbol1DocHandlingUnitSeqNbr_AT[a] = null;
      OutGrpDocHandlingUnitIbol1DocHandlingUnitSeqNbr_AS[a] = ' ';
      OutGrpDocHandlingUnitIbol1DocHandlingUnitSeqNbr[a] = 0;
      OutGrpDocHandlingUnitIbol1DocHandlingUnitCreateDt_AT[a] = null;
      OutGrpDocHandlingUnitIbol1DocHandlingUnitCreateDt_AS[a] = ' ';
      OutGrpDocHandlingUnitIbol1DocHandlingUnitCreateDt[a] = 00000000;
    }
    OutErrorIshs1SharedServicesDataStoreStatusCd_AT = null;
    OutErrorIshs1SharedServicesDataStoreStatusCd_AS = ' ';
    OutErrorIshs1SharedServicesDataStoreStatusCd = " ";
    OutErrorIshs1SharedServicesOriginServerId_AT = null;
    OutErrorIshs1SharedServicesOriginServerId_AS = ' ';
    OutErrorIshs1SharedServicesOriginServerId = 0.0;
    OutErrorIshs1SharedServicesContextStringTx_AT = null;
    OutErrorIshs1SharedServicesContextStringTx_AS = ' ';
    OutErrorIshs1SharedServicesContextStringTx = "";
    OutErrorIshs1SharedServicesReturnCd_AT = null;
    OutErrorIshs1SharedServicesReturnCd_AS = ' ';
    OutErrorIshs1SharedServicesReturnCd = 0;
    OutErrorIshs1SharedServicesReasonCd_AT = null;
    OutErrorIshs1SharedServicesReasonCd_AS = ' ';
    OutErrorIshs1SharedServicesReasonCd = 0;
  }
  /**
   * Gets the VDF array for the instance, initialized.
   **/
  
  public static VDF getViewDefinition()
  {
    if ( localVdf == null )
    {
      VDFEntry [] vdfEntries = {
        new VDFEntry((int)1, "OutGroupDocHandlingUnits", "", "", "MA", VDFEntry.TYPE_INT, (short)1, (short)0, 4, (short)0, null), 
        new VDFEntry((int)2, "OutGroupDocHandlingUnits", "", "", "AC", VDFEntry.TYPE_CHAR, (short)200, (short)0, 1, (short)0, null), 
          
        new VDFEntry((int)3, "OutGroupDocHandlingUnits", "OutGrpDocHandlingUnitIbol1DocHandlingUnit", "Ibol1DocHandlingUnit", 
          "ChildProNbrTxt", VDFEntry.TYPE_STRING, (short)200, (short)0, 11, (short)0, null), 
        new VDFEntry((int)4, "OutGroupDocHandlingUnits", "OutGrpDocHandlingUnitIbol1DocHandlingUnit", "Ibol1DocHandlingUnit", 
          "BolInstId", VDFEntry.TYPE_DOUBLE, (short)200, (short)0, 15, (short)0, null), 
        new VDFEntry((int)5, "OutGroupDocHandlingUnits", "OutGrpDocHandlingUnitIbol1DocHandlingUnit", "Ibol1DocHandlingUnit", 
          "SeqNbr", VDFEntry.TYPE_SHORT, (short)200, (short)0, 2, (short)0, null), 
        new VDFEntry((int)6, "OutGroupDocHandlingUnits", "OutGrpDocHandlingUnitIbol1DocHandlingUnit", "Ibol1DocHandlingUnit", 
          "CreateDt", VDFEntry.TYPE_DATE, (short)200, (short)0, 8, (short)0, null), 
        new VDFEntry((int)7, "", "OutErrorIshs1SharedServices", "Ishs1SharedServices", "DataStoreStatusCd", VDFEntry.TYPE_STRING, (
          short)1, (short)0, 1, (short)0, null), 
        new VDFEntry((int)8, "", "OutErrorIshs1SharedServices", "Ishs1SharedServices", "OriginServerId", VDFEntry.TYPE_DOUBLE, (
          short)1, (short)0, 15, (short)0, null), 
        new VDFEntry((int)9, "", "OutErrorIshs1SharedServices", "Ishs1SharedServices", "ContextStringTx", VDFEntry.TYPE_STRING, (
          short)1, (short)0, 255, (short)0, null), 
        new VDFEntry((int)10, "", "OutErrorIshs1SharedServices", "Ishs1SharedServices", "ReturnCd", VDFEntry.TYPE_INT, (short)1, (
          short)0, 8, (short)0, null), 
        new VDFEntry((int)11, "", "OutErrorIshs1SharedServices", "Ishs1SharedServices", "ReasonCd", VDFEntry.TYPE_INT, (short)1, (
          short)0, 8, (short)0, null), 
      };
      localVdf = new VDF(vdfEntries);
    }
    try {
      VDF result = (VDF)localVdf.clone();
      result.initViewData();
      return result;
    } catch( CloneNotSupportedException e ) {
      return null;
    }
  }
  
  /**
   * Sets the current state of the instance to the VDF version.
   **/
  public void setFromVDF(VDF vdf)
  {
    // group view current cardinality
    if ( vdf.getEntries()[0].getDataValue().getObject() != null )
    {
      OutGroupDocHandlingUnits_MA = ((Integer)vdf.getEntries()[0].getDataValue().getObject()).intValue();
    }
    else 
    {
      OutGroupDocHandlingUnits_MA = 0;
    }
    // group view active flags
    for(int adim0 = 0; adim0 < OutGroupDocHandlingUnits_MA; adim0++)
    {
      if ( ((VDFEntryObject [])vdf.getEntries()[1].getDataValue().getObject())[adim0].getObject() != null )
      {
        OutGroupDocHandlingUnits_AC[adim0] = ((Character)((VDFEntryObject [])vdf.getEntries()[1].getDataValue().getObject())[adim0]
          .getObject()).charValue();
      }
      else 
      {
        OutGroupDocHandlingUnits_AC[adim0] = ' ';
      }
    }
    // current cardinality group view items
    for(int adim0 = 0; adim0 < OutGroupDocHandlingUnits_MA; adim0++)
    {
      if ( ((VDFEntryObject [])vdf.getEntries()[2].getDataValue().getObject())[adim0].getObject() != null )
      {
        OutGrpDocHandlingUnitIbol1DocHandlingUnitChildProNbrTxt[adim0] = ((String)((VDFEntryObject [])vdf.getEntries()[2]
          .getDataValue().getObject())[adim0].getObject());
      }
      else 
      {
        OutGrpDocHandlingUnitIbol1DocHandlingUnitChildProNbrTxt[adim0] = "           ";
      }
    }
    // current cardinality group view items
    for(int adim0 = 0; adim0 < OutGroupDocHandlingUnits_MA; adim0++)
    {
      if ( ((VDFEntryObject [])vdf.getEntries()[3].getDataValue().getObject())[adim0].getObject() != null )
      {
        OutGrpDocHandlingUnitIbol1DocHandlingUnitBolInstId[adim0] = ((Double)((VDFEntryObject [])vdf.getEntries()[3].getDataValue()
          .getObject())[adim0].getObject()).doubleValue();
      }
      else 
      {
        OutGrpDocHandlingUnitIbol1DocHandlingUnitBolInstId[adim0] = 0.0;
      }
    }
    // current cardinality group view items
    for(int adim0 = 0; adim0 < OutGroupDocHandlingUnits_MA; adim0++)
    {
      if ( ((VDFEntryObject [])vdf.getEntries()[4].getDataValue().getObject())[adim0].getObject() != null )
      {
        OutGrpDocHandlingUnitIbol1DocHandlingUnitSeqNbr[adim0] = ((Short)((VDFEntryObject [])vdf.getEntries()[4].getDataValue()
          .getObject())[adim0].getObject()).shortValue();
      }
      else 
      {
        OutGrpDocHandlingUnitIbol1DocHandlingUnitSeqNbr[adim0] = 0;
      }
    }
    // current cardinality group view items
    for(int adim0 = 0; adim0 < OutGroupDocHandlingUnits_MA; adim0++)
    {
      if ( ((VDFEntryObject [])vdf.getEntries()[5].getDataValue().getObject())[adim0].getObject() != null )
      {
        OutGrpDocHandlingUnitIbol1DocHandlingUnitCreateDt[adim0] = ((Integer)((VDFEntryObject [])vdf.getEntries()[5].getDataValue()
          .getObject())[adim0].getObject()).intValue();
      }
      else 
      {
        OutGrpDocHandlingUnitIbol1DocHandlingUnitCreateDt[adim0] = 00000000;
      }
    }
    // predicate view item
    if ( vdf.getEntries()[6].getDataValue().getObject() != null )
    {
      OutErrorIshs1SharedServicesDataStoreStatusCd = ((String)vdf.getEntries()[6].getDataValue().getObject());
    }
    else 
    {
      OutErrorIshs1SharedServicesDataStoreStatusCd = " ";
    }
    // predicate view item
    if ( vdf.getEntries()[7].getDataValue().getObject() != null )
    {
      OutErrorIshs1SharedServicesOriginServerId = ((Double)vdf.getEntries()[7].getDataValue().getObject()).doubleValue();
    }
    else 
    {
      OutErrorIshs1SharedServicesOriginServerId = 0.0;
    }
    // predicate view item
    if ( vdf.getEntries()[8].getDataValue().getObject() != null )
    {
      OutErrorIshs1SharedServicesContextStringTx = ((String)vdf.getEntries()[8].getDataValue().getObject());
    }
    else 
    {
      OutErrorIshs1SharedServicesContextStringTx = "";
    }
    // predicate view item
    if ( vdf.getEntries()[9].getDataValue().getObject() != null )
    {
      OutErrorIshs1SharedServicesReturnCd = ((Integer)vdf.getEntries()[9].getDataValue().getObject()).intValue();
    }
    else 
    {
      OutErrorIshs1SharedServicesReturnCd = 0;
    }
    // predicate view item
    if ( vdf.getEntries()[10].getDataValue().getObject() != null )
    {
      OutErrorIshs1SharedServicesReasonCd = ((Integer)vdf.getEntries()[10].getDataValue().getObject()).intValue();
    }
    else 
    {
      OutErrorIshs1SharedServicesReasonCd = 0;
    }
  }
  
  /**
   * Gets the VDF version of the current state of the instance.
   **/
  public VDF getVDF()
  {
    VDF vdf = getViewDefinition();
    // group view current cardinality
    vdf.getEntries()[0].getDataValue().setObject(new Integer(OutGroupDocHandlingUnits_MA));
    // group view active flags
    for(int adim0 = 0; adim0 < 200; adim0++)
    {
      if ( adim0 < OutGroupDocHandlingUnits_MA )
      {
        ((VDFEntryObject [])vdf.getEntries()[1].getDataValue().getObject())[adim0].setObject(new Character('Y'));
      }
      else 
      {
        ((VDFEntryObject [])vdf.getEntries()[1].getDataValue().getObject())[adim0].setObject(new Character('N'));
      }
    }
    vdf.getEntries()[1].setCountUsed((short)OutGroupDocHandlingUnits_MA);
    // current cardinality group view items
    for(int adim0 = 0; adim0 < 200; adim0++)
    {
      ((VDFEntryObject [])vdf.getEntries()[2].getDataValue().getObject())[adim0].setObject(
        OutGrpDocHandlingUnitIbol1DocHandlingUnitChildProNbrTxt[adim0]);
    }
    vdf.getEntries()[2].setCountUsed((short)OutGroupDocHandlingUnits_MA);
    // current cardinality group view items
    for(int adim0 = 0; adim0 < 200; adim0++)
    {
      ((VDFEntryObject [])vdf.getEntries()[3].getDataValue().getObject())[adim0].setObject(new Double(
        OutGrpDocHandlingUnitIbol1DocHandlingUnitBolInstId[adim0]));
    }
    vdf.getEntries()[3].setCountUsed((short)OutGroupDocHandlingUnits_MA);
    // current cardinality group view items
    for(int adim0 = 0; adim0 < 200; adim0++)
    {
      ((VDFEntryObject [])vdf.getEntries()[4].getDataValue().getObject())[adim0].setObject(new Short(
        OutGrpDocHandlingUnitIbol1DocHandlingUnitSeqNbr[adim0]));
    }
    vdf.getEntries()[4].setCountUsed((short)OutGroupDocHandlingUnits_MA);
    // current cardinality group view items
    for(int adim0 = 0; adim0 < 200; adim0++)
    {
      ((VDFEntryObject [])vdf.getEntries()[5].getDataValue().getObject())[adim0].setObject(new Integer(
        OutGrpDocHandlingUnitIbol1DocHandlingUnitCreateDt[adim0]));
    }
    vdf.getEntries()[5].setCountUsed((short)OutGroupDocHandlingUnits_MA);
    // predicate view item
    vdf.getEntries()[6].getDataValue().setObject(OutErrorIshs1SharedServicesDataStoreStatusCd);
    // predicate view item
    vdf.getEntries()[7].getDataValue().setObject(new Double(OutErrorIshs1SharedServicesOriginServerId));
    // predicate view item
    vdf.getEntries()[8].getDataValue().setObject(OutErrorIshs1SharedServicesContextStringTx);
    // predicate view item
    vdf.getEntries()[9].getDataValue().setObject(new Integer(OutErrorIshs1SharedServicesReturnCd));
    // predicate view item
    vdf.getEntries()[10].getDataValue().setObject(new Integer(OutErrorIshs1SharedServicesReasonCd));
    return(vdf);
  }
  
  /**
   * Sets the current instance based on the passed view.
   **/
  public void copyFrom(IExportView orig)
  {
    this.copyFrom((BO11S000_OA) orig);
  }
  
  /**
   * Sets the current instance based on the passed view.
   **/
  public void copyFrom(BO11S000_OA orig)
  {
    OutGroupDocHandlingUnits_MA = orig.OutGroupDocHandlingUnits_MA;
    for(int a = 0; a < 200; a++)
    {
      OutGroupDocHandlingUnits_AC[a] = orig.OutGroupDocHandlingUnits_AC[a];
      OutGrpDocHandlingUnitIbol1DocHandlingUnitChildProNbrTxt_AT[a] = 
        orig.OutGrpDocHandlingUnitIbol1DocHandlingUnitChildProNbrTxt_AT[a];
      OutGrpDocHandlingUnitIbol1DocHandlingUnitChildProNbrTxt_AS[a] = 
        orig.OutGrpDocHandlingUnitIbol1DocHandlingUnitChildProNbrTxt_AS[a];
      OutGrpDocHandlingUnitIbol1DocHandlingUnitChildProNbrTxt[a] = orig.OutGrpDocHandlingUnitIbol1DocHandlingUnitChildProNbrTxt[a];
      OutGrpDocHandlingUnitIbol1DocHandlingUnitBolInstId_AT[a] = orig.OutGrpDocHandlingUnitIbol1DocHandlingUnitBolInstId_AT[a];
      OutGrpDocHandlingUnitIbol1DocHandlingUnitBolInstId_AS[a] = orig.OutGrpDocHandlingUnitIbol1DocHandlingUnitBolInstId_AS[a];
      OutGrpDocHandlingUnitIbol1DocHandlingUnitBolInstId[a] = orig.OutGrpDocHandlingUnitIbol1DocHandlingUnitBolInstId[a];
      OutGrpDocHandlingUnitIbol1DocHandlingUnitSeqNbr_AT[a] = orig.OutGrpDocHandlingUnitIbol1DocHandlingUnitSeqNbr_AT[a];
      OutGrpDocHandlingUnitIbol1DocHandlingUnitSeqNbr_AS[a] = orig.OutGrpDocHandlingUnitIbol1DocHandlingUnitSeqNbr_AS[a];
      OutGrpDocHandlingUnitIbol1DocHandlingUnitSeqNbr[a] = orig.OutGrpDocHandlingUnitIbol1DocHandlingUnitSeqNbr[a];
      OutGrpDocHandlingUnitIbol1DocHandlingUnitCreateDt_AT[a] = orig.OutGrpDocHandlingUnitIbol1DocHandlingUnitCreateDt_AT[a];
      OutGrpDocHandlingUnitIbol1DocHandlingUnitCreateDt_AS[a] = orig.OutGrpDocHandlingUnitIbol1DocHandlingUnitCreateDt_AS[a];
      OutGrpDocHandlingUnitIbol1DocHandlingUnitCreateDt[a] = orig.OutGrpDocHandlingUnitIbol1DocHandlingUnitCreateDt[a];
    }
    OutErrorIshs1SharedServicesDataStoreStatusCd_AT = orig.OutErrorIshs1SharedServicesDataStoreStatusCd_AT;
    OutErrorIshs1SharedServicesDataStoreStatusCd_AS = orig.OutErrorIshs1SharedServicesDataStoreStatusCd_AS;
    OutErrorIshs1SharedServicesDataStoreStatusCd = orig.OutErrorIshs1SharedServicesDataStoreStatusCd;
    OutErrorIshs1SharedServicesOriginServerId_AT = orig.OutErrorIshs1SharedServicesOriginServerId_AT;
    OutErrorIshs1SharedServicesOriginServerId_AS = orig.OutErrorIshs1SharedServicesOriginServerId_AS;
    OutErrorIshs1SharedServicesOriginServerId = orig.OutErrorIshs1SharedServicesOriginServerId;
    OutErrorIshs1SharedServicesContextStringTx_AT = orig.OutErrorIshs1SharedServicesContextStringTx_AT;
    OutErrorIshs1SharedServicesContextStringTx_AS = orig.OutErrorIshs1SharedServicesContextStringTx_AS;
    OutErrorIshs1SharedServicesContextStringTx = orig.OutErrorIshs1SharedServicesContextStringTx;
    OutErrorIshs1SharedServicesReturnCd_AT = orig.OutErrorIshs1SharedServicesReturnCd_AT;
    OutErrorIshs1SharedServicesReturnCd_AS = orig.OutErrorIshs1SharedServicesReturnCd_AS;
    OutErrorIshs1SharedServicesReturnCd = orig.OutErrorIshs1SharedServicesReturnCd;
    OutErrorIshs1SharedServicesReasonCd_AT = orig.OutErrorIshs1SharedServicesReasonCd_AT;
    OutErrorIshs1SharedServicesReasonCd_AS = orig.OutErrorIshs1SharedServicesReasonCd_AS;
    OutErrorIshs1SharedServicesReasonCd = orig.OutErrorIshs1SharedServicesReasonCd;
  }
}
