package proxy.bol.io;
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
//
//                    Source Code Generated by
//                           CA Gen 8.6
//
//    Copyright (c) 2021 CA Technologies. All rights reserved.
//
//    Name: BO11S000_IA                      Date: 2021/01/07
//    User: sehgal.suneet                    Time: 21:18:18
//
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
// Import Statements
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
import java.lang.*;
import java.io.*;
import java.util.*;
import java.math.*;
import java.sql.*;
import com.ca.gen.vwrt.*;
import com.ca.gen.vwrt.types.*;
import com.ca.gen.vwrt.vdf.*;
import com.ca.gen.csu.exception.*;

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
// START OF IMPORT VIEW
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
/**
 * Internal data view storage for: BO11S000_IA
 **/
public class BO11S000_IA extends ViewBase implements IImportView, Serializable
{
  static VDF localVdf = null;
  
  // Entity View: IN
  //        Type: IBOL1_DOC
  /**
   * Attribute missing flag for: InIbol1DocBolInstId
   **/
  public char InIbol1DocBolInstId_AS;
  /**
   * Attribute for: InIbol1DocBolInstId
   * Domain: Number
   * Length: 15
   * Decimal Places: 0
   * Decimal Precision: N
   **/
  public double InIbol1DocBolInstId;
  /**
   * Attribute missing flag for: InIbol1DocProNbrTxt
   **/
  public char InIbol1DocProNbrTxt_AS;
  /**
   * Attribute for: InIbol1DocProNbrTxt
   * Domain: Text
   * Length: 11
   * Varying Length: N
   **/
  public String InIbol1DocProNbrTxt;
  /**
   * Attribute missing flag for: InIbol1DocCustSuppliedProNbrTxt
   **/
  public char InIbol1DocCustSuppliedProNbrTxt_AS;
  /**
   * Attribute for: InIbol1DocCustSuppliedProNbrTxt
   * Domain: Text
   * Length: 11
   * Varying Length: N
   **/
  public String InIbol1DocCustSuppliedProNbrTxt;
  // Repeating GV:  IN_GROUP
  //     Repeats: 200 times
  /**
   * Repeating group view count
   **/
  public int InGroup_MA;
  /**
   * Repeating group view occurrance array
   **/
  public char InGroup_AC[] = new char[200];
  // Entity View: IN_GRP
  //        Type: IBOL1_DOC_HANDLING_UNIT
  /**
   * Attribute missing flag for: InGrpIbol1DocHandlingUnitChildProNbrTxt
   **/
  public char InGrpIbol1DocHandlingUnitChildProNbrTxt_AS[] = new char[200];
  /**
   * Attribute for: InGrpIbol1DocHandlingUnitChildProNbrTxt
   * Domain: Text
   * Length: 11
   * Varying Length: N
   **/
  public String InGrpIbol1DocHandlingUnitChildProNbrTxt[] = new String[200];
  // Entity View: IN_CONTROL
  //        Type: ISHS1_SHARED_SERVICES
  /**
   * Attribute missing flag for: InControlIshs1SharedServicesLongUserid
   **/
  public char InControlIshs1SharedServicesLongUserid_AS;
  /**
   * Attribute for: InControlIshs1SharedServicesLongUserid
   * Domain: Text
   * Length: 15
   * Varying Length: N
   **/
  public String InControlIshs1SharedServicesLongUserid;
  /**
   * Attribute missing flag for: InControlIshs1SharedServicesUserId
   **/
  public char InControlIshs1SharedServicesUserId_AS;
  /**
   * Attribute for: InControlIshs1SharedServicesUserId
   * Domain: Text
   * Length: 8
   * Varying Length: N
   **/
  public String InControlIshs1SharedServicesUserId;
  /**
   * Attribute missing flag for: InControlIshs1SharedServicesDateDt
   **/
  public char InControlIshs1SharedServicesDateDt_AS;
  /**
   * Attribute for: InControlIshs1SharedServicesDateDt
   * Domain: Date
   * Length: 8
   **/
  public int InControlIshs1SharedServicesDateDt;
  /**
   * Attribute missing flag for: InControlIshs1SharedServicesTimestampTs
   **/
  public char InControlIshs1SharedServicesTimestampTs_AS;
  /**
   * Attribute for: InControlIshs1SharedServicesTimestampTs
   * Domain: Timestamp
   * Length: 20
   **/
  public String InControlIshs1SharedServicesTimestampTs;
  /**
   * Attribute missing flag for: InControlIshs1SharedServicesTranCd
   **/
  public char InControlIshs1SharedServicesTranCd_AS;
  /**
   * Attribute for: InControlIshs1SharedServicesTranCd
   * Domain: Text
   * Length: 8
   * Varying Length: N
   **/
  public String InControlIshs1SharedServicesTranCd;
  /**
   * Attribute missing flag for: InControlIshs1SharedServicesVersionCheckTs
   **/
  public char InControlIshs1SharedServicesVersionCheckTs_AS;
  /**
   * Attribute for: InControlIshs1SharedServicesVersionCheckTs
   * Domain: Timestamp
   * Length: 20
   **/
  public String InControlIshs1SharedServicesVersionCheckTs;
  /**
   * Default Constructor
   **/
  
  public BO11S000_IA()
  {
    reset();
  }
  /**
   * Copy Constructor
   **/
  
  public BO11S000_IA(BO11S000_IA orig)
  {
    copyFrom(orig);
  }
  /**
   * Static instance creator function
   **/
  
  public static BO11S000_IA getInstance()
  {
    return new BO11S000_IA();
  }
  /**
   * Static free instance method
   **/
  
  public void freeInstance()
  {
  }
  /**
   * clone constructor
   **/
  
  @Override public Object clone()
  	throws CloneNotSupportedException
  {
    return(new BO11S000_IA(this));
  }
  /**
   * Resets all properties to the defaults.
   **/
  
  public void reset()
  {
    InIbol1DocBolInstId_AS = ' ';
    InIbol1DocBolInstId = 0.0;
    InIbol1DocProNbrTxt_AS = ' ';
    InIbol1DocProNbrTxt = "           ";
    InIbol1DocCustSuppliedProNbrTxt_AS = ' ';
    InIbol1DocCustSuppliedProNbrTxt = "           ";
    InGroup_MA = 0;
    for(int a = 0; a < 200; a++)
    {
      InGroup_AC[a] = ' ';
      InGrpIbol1DocHandlingUnitChildProNbrTxt_AS[a] = ' ';
      InGrpIbol1DocHandlingUnitChildProNbrTxt[a] = "           ";
    }
    InControlIshs1SharedServicesLongUserid_AS = ' ';
    InControlIshs1SharedServicesLongUserid = "               ";
    InControlIshs1SharedServicesUserId_AS = ' ';
    InControlIshs1SharedServicesUserId = "        ";
    InControlIshs1SharedServicesDateDt_AS = ' ';
    InControlIshs1SharedServicesDateDt = 00000000;
    InControlIshs1SharedServicesTimestampTs_AS = ' ';
    InControlIshs1SharedServicesTimestampTs = "00000000000000000000";
    InControlIshs1SharedServicesTranCd_AS = ' ';
    InControlIshs1SharedServicesTranCd = "        ";
    InControlIshs1SharedServicesVersionCheckTs_AS = ' ';
    InControlIshs1SharedServicesVersionCheckTs = "00000000000000000000";
  }
  /**
   * Gets the VDF array for the instance, initialized.
   **/
  
  public static VDF getViewDefinition()
  {
    if ( localVdf == null )
    {
      VDFEntry [] vdfEntries = {
        new VDFEntry((int)1, "", "InIbol1Doc", "Ibol1Doc", "BolInstId", VDFEntry.TYPE_DOUBLE, (short)1, (short)0, 15, (short)0, null)
          , 
        new VDFEntry((int)2, "", "InIbol1Doc", "Ibol1Doc", "ProNbrTxt", VDFEntry.TYPE_STRING, (short)1, (short)0, 11, (short)0, null)
          , 
        new VDFEntry((int)3, "", "InIbol1Doc", "Ibol1Doc", "CustSuppliedProNbrTxt", VDFEntry.TYPE_STRING, (short)1, (short)0, 11, (
          short)0, null), 
        new VDFEntry((int)4, "InGroup", "", "", "MA", VDFEntry.TYPE_INT, (short)1, (short)0, 4, (short)0, null), 
        new VDFEntry((int)5, "InGroup", "", "", "AC", VDFEntry.TYPE_CHAR, (short)200, (short)0, 1, (short)0, null), 
        new VDFEntry((int)6, "InGroup", "InGrpIbol1DocHandlingUnit", "Ibol1DocHandlingUnit", "ChildProNbrTxt", VDFEntry.TYPE_STRING, 
          (short)200, (short)0, 11, (short)0, null), 
        new VDFEntry((int)7, "", "InControlIshs1SharedServices", "Ishs1SharedServices", "LongUserid", VDFEntry.TYPE_STRING, (short)1,
           (short)0, 15, (short)0, null), 
        new VDFEntry((int)8, "", "InControlIshs1SharedServices", "Ishs1SharedServices", "UserId", VDFEntry.TYPE_STRING, (short)1, (
          short)0, 8, (short)0, null), 
        new VDFEntry((int)9, "", "InControlIshs1SharedServices", "Ishs1SharedServices", "DateDt", VDFEntry.TYPE_DATE, (short)1, (
          short)0, 8, (short)0, null), 
        new VDFEntry((int)10, "", "InControlIshs1SharedServices", "Ishs1SharedServices", "TimestampTs", VDFEntry.TYPE_TIMESTAMP, (
          short)1, (short)0, 20, (short)0, null), 
        new VDFEntry((int)11, "", "InControlIshs1SharedServices", "Ishs1SharedServices", "TranCd", VDFEntry.TYPE_STRING, (short)1, (
          short)0, 8, (short)0, null), 
        new VDFEntry((int)12, "", "InControlIshs1SharedServices", "Ishs1SharedServices", "VersionCheckTs", VDFEntry.TYPE_TIMESTAMP, (
          short)1, (short)0, 20, (short)0, null), 
      };
      localVdf = new VDF(vdfEntries);
    }
    try {
      VDF result = (VDF)localVdf.clone();
      result.initViewData();
      return result;
    } catch( CloneNotSupportedException e ) {
      return null;
    }
  }
  
  /**
   * Gets the VDF version of the current state of the instance.
   **/
  public VDF getVDF()
  {
    VDF vdf = getViewDefinition();
    // predicate view item
    vdf.getEntries()[0].getDataValue().setObject(new Double(InIbol1DocBolInstId));
    // predicate view item
    vdf.getEntries()[1].getDataValue().setObject(InIbol1DocProNbrTxt);
    // predicate view item
    vdf.getEntries()[2].getDataValue().setObject(InIbol1DocCustSuppliedProNbrTxt);
    // group view current cardinality
    vdf.getEntries()[3].getDataValue().setObject(new Integer(InGroup_MA));
    // group view active flags
    for(int adim0 = 0; adim0 < 200; adim0++)
    {
      if ( adim0 < InGroup_MA )
      {
        ((VDFEntryObject [])vdf.getEntries()[4].getDataValue().getObject())[adim0].setObject(new Character('Y'));
      }
      else 
      {
        ((VDFEntryObject [])vdf.getEntries()[4].getDataValue().getObject())[adim0].setObject(new Character('N'));
      }
    }
    vdf.getEntries()[4].setCountUsed((short)InGroup_MA);
    // current cardinality group view items
    for(int adim0 = 0; adim0 < 200; adim0++)
    {
      ((VDFEntryObject [])vdf.getEntries()[5].getDataValue().getObject())[adim0].setObject(InGrpIbol1DocHandlingUnitChildProNbrTxt[
        adim0]);
    }
    vdf.getEntries()[5].setCountUsed((short)InGroup_MA);
    // predicate view item
    vdf.getEntries()[6].getDataValue().setObject(InControlIshs1SharedServicesLongUserid);
    // predicate view item
    vdf.getEntries()[7].getDataValue().setObject(InControlIshs1SharedServicesUserId);
    // predicate view item
    vdf.getEntries()[8].getDataValue().setObject(new Integer(InControlIshs1SharedServicesDateDt));
    // predicate view item
    vdf.getEntries()[9].getDataValue().setObject(InControlIshs1SharedServicesTimestampTs);
    // predicate view item
    vdf.getEntries()[10].getDataValue().setObject(InControlIshs1SharedServicesTranCd);
    // predicate view item
    vdf.getEntries()[11].getDataValue().setObject(InControlIshs1SharedServicesVersionCheckTs);
    return(vdf);
  }
  
  /**
   * Sets the current state of the instance to the VDF version.
   **/
  public void setFromVDF(VDF vdf)
  {
    // predicate view item
    if ( vdf.getEntries()[0].getDataValue().getObject() != null )
    {
      InIbol1DocBolInstId = ((Double)vdf.getEntries()[0].getDataValue().getObject()).doubleValue();
    }
    else 
    {
      InIbol1DocBolInstId = 0.0;
    }
    // predicate view item
    if ( vdf.getEntries()[1].getDataValue().getObject() != null )
    {
      InIbol1DocProNbrTxt = ((String)vdf.getEntries()[1].getDataValue().getObject());
    }
    else 
    {
      InIbol1DocProNbrTxt = "           ";
    }
    // predicate view item
    if ( vdf.getEntries()[2].getDataValue().getObject() != null )
    {
      InIbol1DocCustSuppliedProNbrTxt = ((String)vdf.getEntries()[2].getDataValue().getObject());
    }
    else 
    {
      InIbol1DocCustSuppliedProNbrTxt = "           ";
    }
    // group view current cardinality
    if ( vdf.getEntries()[3].getDataValue().getObject() != null )
    {
      InGroup_MA = ((Integer)vdf.getEntries()[3].getDataValue().getObject()).intValue();
    }
    else 
    {
      InGroup_MA = 0;
    }
    // group view active flags
    for(int adim0 = 0; adim0 < InGroup_MA; adim0++)
    {
      if ( ((VDFEntryObject [])vdf.getEntries()[4].getDataValue().getObject())[adim0].getObject() != null )
      {
        InGroup_AC[adim0] = ((Character)((VDFEntryObject [])vdf.getEntries()[4].getDataValue().getObject())[adim0].getObject())
          .charValue();
      }
      else 
      {
        InGroup_AC[adim0] = ' ';
      }
    }
    // current cardinality group view items
    for(int adim0 = 0; adim0 < InGroup_MA; adim0++)
    {
      if ( ((VDFEntryObject [])vdf.getEntries()[5].getDataValue().getObject())[adim0].getObject() != null )
      {
        InGrpIbol1DocHandlingUnitChildProNbrTxt[adim0] = ((String)((VDFEntryObject [])vdf.getEntries()[5].getDataValue().getObject())
          [adim0].getObject());
      }
      else 
      {
        InGrpIbol1DocHandlingUnitChildProNbrTxt[adim0] = "           ";
      }
    }
    // predicate view item
    if ( vdf.getEntries()[6].getDataValue().getObject() != null )
    {
      InControlIshs1SharedServicesLongUserid = ((String)vdf.getEntries()[6].getDataValue().getObject());
    }
    else 
    {
      InControlIshs1SharedServicesLongUserid = "               ";
    }
    // predicate view item
    if ( vdf.getEntries()[7].getDataValue().getObject() != null )
    {
      InControlIshs1SharedServicesUserId = ((String)vdf.getEntries()[7].getDataValue().getObject());
    }
    else 
    {
      InControlIshs1SharedServicesUserId = "        ";
    }
    // predicate view item
    if ( vdf.getEntries()[8].getDataValue().getObject() != null )
    {
      InControlIshs1SharedServicesDateDt = ((Integer)vdf.getEntries()[8].getDataValue().getObject()).intValue();
    }
    else 
    {
      InControlIshs1SharedServicesDateDt = 00000000;
    }
    // predicate view item
    if ( vdf.getEntries()[9].getDataValue().getObject() != null )
    {
      InControlIshs1SharedServicesTimestampTs = ((String)vdf.getEntries()[9].getDataValue().getObject());
    }
    else 
    {
      InControlIshs1SharedServicesTimestampTs = "00000000000000000000";
    }
    // predicate view item
    if ( vdf.getEntries()[10].getDataValue().getObject() != null )
    {
      InControlIshs1SharedServicesTranCd = ((String)vdf.getEntries()[10].getDataValue().getObject());
    }
    else 
    {
      InControlIshs1SharedServicesTranCd = "        ";
    }
    // predicate view item
    if ( vdf.getEntries()[11].getDataValue().getObject() != null )
    {
      InControlIshs1SharedServicesVersionCheckTs = ((String)vdf.getEntries()[11].getDataValue().getObject());
    }
    else 
    {
      InControlIshs1SharedServicesVersionCheckTs = "00000000000000000000";
    }
  }
  
  /**
   * Sets the current instance based on the passed view.
   **/
  public void copyFrom(IImportView orig)
  {
    this.copyFrom((BO11S000_IA) orig);
  }
  
  /**
   * Sets the current instance based on the passed view.
   **/
  public void copyFrom(BO11S000_IA orig)
  {
    InIbol1DocBolInstId_AS = orig.InIbol1DocBolInstId_AS;
    InIbol1DocBolInstId = orig.InIbol1DocBolInstId;
    InIbol1DocProNbrTxt_AS = orig.InIbol1DocProNbrTxt_AS;
    InIbol1DocProNbrTxt = orig.InIbol1DocProNbrTxt;
    InIbol1DocCustSuppliedProNbrTxt_AS = orig.InIbol1DocCustSuppliedProNbrTxt_AS;
    InIbol1DocCustSuppliedProNbrTxt = orig.InIbol1DocCustSuppliedProNbrTxt;
    InGroup_MA = orig.InGroup_MA;
    for(int a = 0; a < 200; a++)
    {
      InGroup_AC[a] = orig.InGroup_AC[a];
      InGrpIbol1DocHandlingUnitChildProNbrTxt_AS[a] = orig.InGrpIbol1DocHandlingUnitChildProNbrTxt_AS[a];
      InGrpIbol1DocHandlingUnitChildProNbrTxt[a] = orig.InGrpIbol1DocHandlingUnitChildProNbrTxt[a];
    }
    InControlIshs1SharedServicesLongUserid_AS = orig.InControlIshs1SharedServicesLongUserid_AS;
    InControlIshs1SharedServicesLongUserid = orig.InControlIshs1SharedServicesLongUserid;
    InControlIshs1SharedServicesUserId_AS = orig.InControlIshs1SharedServicesUserId_AS;
    InControlIshs1SharedServicesUserId = orig.InControlIshs1SharedServicesUserId;
    InControlIshs1SharedServicesDateDt_AS = orig.InControlIshs1SharedServicesDateDt_AS;
    InControlIshs1SharedServicesDateDt = orig.InControlIshs1SharedServicesDateDt;
    InControlIshs1SharedServicesTimestampTs_AS = orig.InControlIshs1SharedServicesTimestampTs_AS;
    InControlIshs1SharedServicesTimestampTs = orig.InControlIshs1SharedServicesTimestampTs;
    InControlIshs1SharedServicesTranCd_AS = orig.InControlIshs1SharedServicesTranCd_AS;
    InControlIshs1SharedServicesTranCd = orig.InControlIshs1SharedServicesTranCd;
    InControlIshs1SharedServicesVersionCheckTs_AS = orig.InControlIshs1SharedServicesVersionCheckTs_AS;
    InControlIshs1SharedServicesVersionCheckTs = orig.InControlIshs1SharedServicesVersionCheckTs;
  }
}
